import Std
import BoundaryPartition
import RspSummary

/-!
## Boundary compiler: finite affine ranges and the seven-slot bound

This file isolates the purely combinatorial counting core of the boundary
compiler.  A fixed owner/opposite-run emits at most eight cut positions:

* two window endpoints (`lo`, `hi+1`);
* two run/corner cuts (`c+1`, `d`) which also handle run-length-one overlap;
* the two RSP spike cuts (`spike`, `spike+1`) on each of the left and right
  edges.

Eight cuts produce at most seven adjacent intervals.  The actual `L`/`R`
strings enter only through four `EdgeRspCertificate`s; the combinatorial core
below is independent of their construction.

The file also records the degenerate edge-overlap interface.  Corners and
length-one runs can make several named edges coincide, but
`edgeMembershipCount_le_four` bounds that overlap by four.
-/

open Lcs RunRect Repair RspSummary

set_option linter.unusedSectionVars false

namespace BoundaryRangeCount

/-! ### Generic affine piece -/

/-- A generic affine piece.  Both coordinates are affine in the integer local
coordinate `z`; domains are the closed natural interval `[lo, hi]`. -/
structure AffinePiece where
  lo : Nat
  hi : Nat
  leftSlope : Int
  leftIntercept : Int
  rightSlope : Int
  rightIntercept : Int
  deriving DecidableEq, Repr

namespace AffinePiece

/-- Left-coordinate value of the affine piece. -/
def leftAt (r : AffinePiece) (z : Nat) : Int :=
  r.leftSlope * (z : Int) + r.leftIntercept

/-- Right-coordinate value of the affine piece. -/
def rightAt (r : AffinePiece) (z : Nat) : Int :=
  r.rightSlope * (z : Int) + r.rightIntercept

/-- The natural interval carried by the piece is nonempty. -/
def Nonempty (r : AffinePiece) : Prop := r.lo ≤ r.hi

end AffinePiece

/-! ### Adjacent cuts and interval capacity -/

/-- Adjacent pairs of a cut list.  Repeated or unsorted cuts are allowed: the
result is a capacity enumeration, and invalid/empty intervals can be discarded
later by sorting in the string-level compiler. -/
def adjacentPairs : List Nat → List (Nat × Nat)
  | [] => []
  | _ :: [] => []
  | x :: y :: xs => (x, y) :: adjacentPairs (y :: xs)

/-- A list of `n` cuts has at most `n-1` adjacent pairs. -/
theorem adjacentPairs_length_le_pred (cuts : List Nat) :
    (adjacentPairs cuts).length ≤ cuts.length - 1 := by
  induction cuts with
  | nil => simp [adjacentPairs]
  | cons x xs ih =>
    cases xs with
    | nil => simp [adjacentPairs]
    | cons y ys =>
      have htail : (adjacentPairs (y :: ys)).length ≤ ys.length := by
        have hi := ih
        simpa using hi
      simp [adjacentPairs]
      omega

/-- Number of adjacent interval slots generated by a cut list. -/
def rangeCount (cuts : List Nat) : Nat := (adjacentPairs cuts).length

/-! ### RSP threshold records -/

/-- The three phases selected by an RSP spike. -/
inductive RspPhase where
  | ramp
  | spike
  | plateau
  deriving DecidableEq, Repr

/-- Phase of a coordinate relative to the RSP spike `m`. -/
def phaseOf (m z : Nat) : RspPhase :=
  if z < m then .ramp else if z = m then .spike else .plateau

/-- `RspShape.threshold` restated as an explicit three-phase membership test.
The two phase cuts are `m` and `m+1`; within each phase the RSP formula is a
single affine/constant expression. -/
theorem rspShape_threshold_phase_iff {f : Nat → Nat} {m γ lo n : Nat}
    (h : RspShape f m γ lo n) {lam z : Nat} (hl : lo ≤ z) (hz : z ≤ n) :
    (lam ≤ f z ↔
      (phaseOf m z = RspPhase.ramp ∧ lam ≤ z) ∨
      (phaseOf m z = RspPhase.spike ∧ lam ≤ m + γ) ∨
      (phaseOf m z = RspPhase.plateau ∧ lam ≤ m)) := by
  rw [h.threshold hl hz]
  unfold phaseOf
  by_cases h1 : z < m
  · have hzm : z ≠ m := by omega
    have hmz : ¬ m < z := by omega
    simp [h1, hzm, hmz]
  · by_cases h2 : z = m
    · simp [h2]
    · have hmz : m < z := by omega
      simp [h1, h2, hmz]

/-- String-independent metadata for one edge RSP.  The `shape` field ties the
record to the exact ramp-spike-plateau theorem. -/
structure EdgeRspCertificate (f : Nat → Nat) where
  lo : Nat
  spike : Nat
  hi : Nat
  gamma : Nat
  shape : RspShape f spike gamma lo hi

/-- Threshold metadata paired with an edge RSP certificate. -/
structure RspThresholdRecord where
  lo : Nat
  spike : Nat
  hi : Nat
  gamma : Nat
  threshold : Nat
  deriving DecidableEq, Repr

/-- Forget the proof-carrying shape and retain the threshold record. -/
def EdgeRspCertificate.toRecord (c : EdgeRspCertificate f) (threshold : Nat) :
    RspThresholdRecord where
  lo := c.lo
  spike := c.spike
  hi := c.hi
  gamma := c.gamma
  threshold := threshold

/-- The two phase cuts contributed by one RSP threshold record. -/
def RspThresholdRecord.phaseCuts (r : RspThresholdRecord) : List Nat :=
  [r.spike, r.spike + 1]

/-- Each RSP phase boundary contributes exactly two cuts. -/
theorem RspThresholdRecord.phaseCuts_length (r : RspThresholdRecord) :
    r.phaseCuts.length = 2 := by
  simp [phaseCuts]

/-- The exact threshold test of an edge RSP certificate. -/
theorem EdgeRspCertificate.threshold_iff (c : EdgeRspCertificate f)
    {lam z : Nat} (hl : c.lo ≤ z) (hz : z ≤ c.hi) :
    (lam ≤ f z ↔
      (phaseOf c.spike z = RspPhase.ramp ∧ lam ≤ z) ∨
      (phaseOf c.spike z = RspPhase.spike ∧ lam ≤ c.spike + c.gamma) ∨
      (phaseOf c.spike z = RspPhase.plateau ∧ lam ≤ c.spike)) :=
  rspShape_threshold_phase_iff c.shape hl hz

/-- Four edge certificates: left, bottom, right, top.  This is the minimal
string-level interface needed by the counting theorem. -/
structure BoundaryRspCertificate
    (fLeft fBottom fRight fTop : Nat → Nat) where
  left : EdgeRspCertificate fLeft
  bottom : EdgeRspCertificate fBottom
  right : EdgeRspCertificate fRight
  top : EdgeRspCertificate fTop

/-- The four records used by the boundary compiler. -/
structure BoundaryEdgeRecords where
  left : RspThresholdRecord
  right : RspThresholdRecord
  bottom : RspThresholdRecord
  top : RspThresholdRecord

namespace BoundaryEdgeRecords

/-- The four records in a fixed edge order. -/
def asList (r : BoundaryEdgeRecords) : List RspThresholdRecord :=
  [r.left, r.right, r.bottom, r.top]

/-- Exactly one RSP record per edge yields four records in total. -/
theorem asList_length (r : BoundaryEdgeRecords) : r.asList.length = 4 := by
  simp [asList]

/-- The edge-record count is bounded by four. -/
theorem length_le_four (r : BoundaryEdgeRecords) : r.asList.length ≤ 4 := by
  rw [r.asList_length]
  omega

/-- All four edge phase boundaries, two cuts per edge. -/
def allRspCuts (r : BoundaryEdgeRecords) : List Nat :=
  r.left.phaseCuts ++ r.bottom.phaseCuts ++ r.right.phaseCuts ++ r.top.phaseCuts

/-- Four edge records contribute exactly eight RSP phase cuts. -/
theorem allRspCuts_length (r : BoundaryEdgeRecords) : r.allRspCuts.length = 8 := by
  simp [allRspCuts, RspThresholdRecord.phaseCuts]

/-- The left/right edge phase cuts used by the one-dimensional compiler. -/
def longitudinalCuts (r : BoundaryEdgeRecords) : List Nat :=
  r.left.phaseCuts ++ r.right.phaseCuts

/-- The two longitudinal RSP records contribute exactly four cuts. -/
theorem longitudinalCuts_length (r : BoundaryEdgeRecords) :
    r.longitudinalCuts.length = 4 := by
  simp [longitudinalCuts, RspThresholdRecord.phaseCuts]

end BoundaryEdgeRecords

/-- Build compiler records from four proof-carrying edge certificates. -/
def BoundaryRspCertificate.toRecords
    (c : BoundaryRspCertificate fLeft fBottom fRight fTop)
    (thrLeft thrBottom thrRight thrTop : Nat) : BoundaryEdgeRecords where
  left := c.left.toRecord thrLeft
  right := c.right.toRecord thrRight
  bottom := c.bottom.toRecord thrBottom
  top := c.top.toRecord thrTop

/-! ### Corner and run-length-one overlap -/

/-- Even in singleton/corner degeneracies, at most four distinct edge labels can
hold at one point. -/
theorem boundary_corner_overlap_le_four (a b c d p u : Nat) :
    BoundaryPartition.edgeMembershipCount a b c d p u ≤ 4 :=
  BoundaryPartition.edgeMembershipCount_le_four a b c d p u

/-- Corner overlap bounded by the number of edge records. -/
theorem boundary_corner_overlap_le_recordCount
    (records : BoundaryEdgeRecords) (a b c d p u : Nat) :
    BoundaryPartition.edgeMembershipCount a b c d p u ≤ records.asList.length := by
  rw [records.asList_length]
  exact boundary_corner_overlap_le_four a b c d p u

/-! ### Eight cuts, seven ranges -/

/-- All data needed by the one-dimensional boundary range compiler.  The
`window` is the clipped causal domain, while `runLo`/`runHi` are the opposite
run endpoints. -/
structure BoundaryRangePlan where
  records : BoundaryEdgeRecords
  windowLo : Nat
  windowHi : Nat
  runLo : Nat
  runHi : Nat

namespace BoundaryRangePlan

/-- The canonical eight compiler cuts. -/
def cutSlots (p : BoundaryRangePlan) : List Nat :=
  [p.windowLo, p.windowHi + 1, p.runLo + 1, p.runHi,
    p.records.left.spike, p.records.left.spike + 1,
    p.records.right.spike, p.records.right.spike + 1]

/-- Exactly eight slots are reserved by the compiler. -/
theorem cutSlots_length (p : BoundaryRangePlan) : p.cutSlots.length = 8 := by
  simp [cutSlots]

/-- The unfiltered compiler capacity is exactly seven adjacent ranges. -/
theorem segmentCapacity_eq_seven (p : BoundaryRangePlan) :
    rangeCount p.cutSlots = 7 := by
  simp [rangeCount, adjacentPairs, cutSlots]

/-- Membership in the clipped half-open cut window `[windowLo, windowHi+1]`. -/
def CutInWindow (p : BoundaryRangePlan) (x : Nat) : Prop :=
  p.windowLo ≤ x ∧ x ≤ p.windowHi + 1

instance (p : BoundaryRangePlan) (x : Nat) : Decidable (p.CutInWindow x) := by
  unfold CutInWindow
  infer_instance

/-- Cuts retained after clipping to the actual owner/opposite-run window. -/
def effectiveCuts (p : BoundaryRangePlan) : List Nat :=
  p.cutSlots.filter (fun x => decide (p.CutInWindow x))

/-- Clipping cannot increase the number of cuts. -/
theorem effectiveCuts_length_le_eight (p : BoundaryRangePlan) :
    p.effectiveCuts.length ≤ 8 := by
  have h := List.length_filter_le (fun x => decide (p.CutInWindow x)) p.cutSlots
  simpa [effectiveCuts, p.cutSlots_length] using h

/-- The clipped compiler emits at most seven ranges. -/
theorem effectiveSegments_length_le_seven (p : BoundaryRangePlan) :
    rangeCount p.effectiveCuts ≤ 7 := by
  have hp := adjacentPairs_length_le_pred p.effectiveCuts
  have hc := p.effectiveCuts_length_le_eight
  unfold rangeCount
  omega

end BoundaryRangePlan

/-- Final pure counting theorem: four edge records, eight canonical cuts, and
clipping/corner overlap still give at most seven effective ranges. -/
theorem boundary_range_count_le_seven
    (records : BoundaryEdgeRecords)
    (windowLo windowHi runLo runHi : Nat) :
    rangeCount
      (BoundaryRangePlan.effectiveCuts
        { records := records
          windowLo := windowLo
          windowHi := windowHi
          runLo := runLo
          runHi := runHi }) ≤ 7 :=
  BoundaryRangePlan.effectiveSegments_length_le_seven _

/-- Combined boundary-compiler core: corner/run-length-one overlap is at most
four edge labels, while the clipped one-dimensional compiler emits at most
seven effective ranges. -/
theorem boundary_corner_overlap_and_range_count_le_seven
    (records : BoundaryEdgeRecords)
    (windowLo windowHi runLo runHi a b c d p u : Nat) :
    BoundaryPartition.edgeMembershipCount a b c d p u ≤ 4 ∧
      rangeCount
        (BoundaryRangePlan.effectiveCuts
          { records := records
            windowLo := windowLo
            windowHi := windowHi
            runLo := runLo
            runHi := runHi }) ≤ 7 := by
  constructor
  · exact boundary_corner_overlap_le_four a b c d p u
  · exact boundary_range_count_le_seven records windowLo windowHi runLo runHi

/-- Same bound after assembling records from a string-level four-edge RSP
certificate. -/
theorem boundary_rsp_certificate_range_count_le_seven
    (cert : BoundaryRspCertificate fLeft fBottom fRight fTop)
    (thrLeft thrBottom thrRight thrTop : Nat)
    (windowLo windowHi runLo runHi : Nat) :
    rangeCount
      (BoundaryRangePlan.effectiveCuts
        { records := cert.toRecords thrLeft thrBottom thrRight thrTop
          windowLo := windowLo
          windowHi := windowHi
          runLo := runLo
          runHi := runHi }) ≤ 7 :=
  boundary_range_count_le_seven _ _ _ _ _

/-! ### Existing string-level instance: the left edge -/

/-- The existing `RspSummary.left_edge_context_rsp` theorem packages the left
edge context into the generic edge certificate interface.  The bottom/top
certificates and one-bit recursive owner clipping are intentionally left to
the string-level assembly layer. -/
def left_edge_certificate
    {q k : Nat → α} {Tq Tk ap bp c d : Nat} {αs' βs : α}
    [DecidableEq α]
    (hQp : ConstRun q Tq ap bp αs') (hK : ConstRun k Tk c d βs)
    (heq : αs' = βs) (hab : ap ≤ bp) (hap : 0 < ap) (hc : 0 < c)
    (hcd : c ≤ d) :
    EdgeRspCertificate (fun z => lcsLen q k bp (c + z - 1)) where
  lo := 1
  spike := bp - ap + 1
  hi := d - c
  gamma := lcsLen q k (ap - 1) (c - 1)
  shape := RspSummary.left_edge_context_rsp
    (q := q) (k := k) (Tq := Tq) (Tk := Tk) (ap := ap) (bp := bp)
    (c := c) (d := d) (αs' := αs') (βs := βs)
    hQp hK heq hab hap hc hcd


/-! ### Another existing string-level instance: the right edge -/

/-- The forward run-rectangle theorem, at the fixed Q-right edge `p = a`,
becomes an RSP in the reflected K offset `z = d-u`. -/
def right_edge_certificate
    {q k : Nat → α} {Tq Tk a b c d : Nat} {αs βs : α}
    [DecidableEq α]
    (hQ : ConstRun q Tq a b αs) (hK : ConstRun k Tk c d βs)
    (heq : αs = βs) (hab : a ≤ b) (hcd : c ≤ d) :
    EdgeRspCertificate (fun z => lcpLen q k Tq Tk a (d - z)) where
  lo := 0
  spike := b - a
  hi := d - c
  gamma := lcpLen q k Tq Tk b d
  shape := by
    refine ⟨?_, ?_, ?_⟩
    · intro z hz0 hz hzn
      have huc : c ≤ d - z := by omega
      have hud : d - z ≤ d := by omega
      have h := RunRectLcp.repair_edge_right_rsp
        (q := q) (k := k) (Tq := Tq) (Tk := Tk)
        (a := a) (b := b) (c := c) (d := d) (αs := αs) (βs := βs)
        hQ hK heq (p := a) (u := d - z) (Nat.le_refl a) hab huc hud
      have hy : d - (d - z) = z := by omega
      rw [hy] at h
      rw [if_neg (by omega : ¬ b - a < z)] at h
      rw [if_neg (by omega : ¬ b - a = z)] at h
      simpa using h
    · intro z hz0 hz hzn
      subst z
      have huc : c ≤ d - (b - a) := by omega
      have hud : d - (b - a) ≤ d := by omega
      have h := RunRectLcp.repair_edge_right_rsp
        (q := q) (k := k) (Tq := Tq) (Tk := Tk)
        (a := a) (b := b) (c := c) (d := d) (αs := αs) (βs := βs)
        hQ hK heq (p := a) (u := d - (b - a)) (Nat.le_refl a) hab huc hud
      have hy : d - (d - (b - a)) = b - a := by omega
      rw [hy] at h
      rw [if_neg (by omega : ¬ b - a < b - a)] at h
      rw [if_pos rfl] at h
      simpa using h
    · intro z hz0 hz hzn
      have huc : c ≤ d - z := by omega
      have hud : d - z ≤ d := by omega
      have h := RunRectLcp.repair_edge_right_rsp
        (q := q) (k := k) (Tq := Tq) (Tk := Tk)
        (a := a) (b := b) (c := c) (d := d) (αs := αs) (βs := βs)
        hQ hK heq (p := a) (u := d - z) (Nat.le_refl a) hab huc hud
      have hy : d - (d - z) = z := by omega
      rw [hy] at h
      rw [if_pos hz] at h
      simpa using h

end BoundaryRangeCount
