import CapacityRunDecomposition
import BoundaryRunExtractor

/-!
## Automatic capacity row covers from finite maximal-run decompositions

This file builds the endpoint-record cover used by the capacity/Q-cut layer
directly from `BoundaryRunExtractor.fullRunList`.

The construction deliberately separates three situations.

* A K-run which is equal-symbol with the Q-run containing `t`, starts after
  zero, and ends before `t` contributes a genuine `CapacityConcrete.RealRun`
  and hence the ordinary/spike `CapacityConcrete.capacityRecords`.
* A K-run with the opposite symbol contributes explicit zero-capacity records.
  The zero proof is `RunRect.run_rectangle_symbol_ne`.
* The remaining boundary cases (a same-symbol run starting at zero, or the
  K-run containing `t`) are represented by exact row records.  Those records
  are kept separate because a maximal run cannot be truncated into a
  `RealRun` without losing its maximality proof.

Thus the exact endpoint list is unconditionally complete for `t ≤ Tk`, while
the `RealRun` sub-list is a `CapacityConcrete.RowCovered` cover exactly when
the explicit coverage hypothesis says that the zero/exact fallback is not
needed.  No termination assumption or maximal-run oracle is introduced.
-/

open BoundaryRunExtractor
open CapacityConcrete
open CapacityMultiRun
open RunRect
open Lcs

set_option linter.unusedSectionVars false
set_option linter.unusedVariables false

namespace BoundaryRunExtractor

namespace RunSeq

/-- Every position below the string length lies in one run of a finite
adjacent run decomposition. -/
theorem exists_run_of_lt
    {α : Type} [DecidableEq α] {s : Nat → α} {T lo : Nat}
    {runs : List (Run s T)} (h : RunSeq s T lo runs)
    {e : Nat} (he : e < T) (hlo : lo ≤ e) :
    ∃ r, r ∈ runs ∧ r.lo ≤ e ∧ e ≤ r.hi := by
  induction h generalizing e with
  | nil hnil =>
      omega
  | cons r hstart htail ih =>
      by_cases hri : e ≤ r.hi
      · exact ⟨r, by simp, by omega, hri⟩
      · have hnext : r.hi + 1 ≤ e := by omega
        obtain ⟨r', hr', hle', hhi'⟩ := ih he hnext
        exact ⟨r', by simp [hr'], hle', hhi'⟩

end RunSeq

end BoundaryRunExtractor

namespace CapacityAutomaticRunCover

variable {α : Type} [DecidableEq α]
variable {q k : Nat → α} {Tq Tk t : Nat}

/-! ### Extracting the Q-run containing `t` -/

/-- A run of the Q string which contains the fixed query position `t`. -/
structure QRunAt (q : Nat → α) (Tq t : Nat) where
  run : Run q Tq
  mem : run ∈ fullRunList q Tq
  lo_le_t : run.lo ≤ t
  t_le_hi : t ≤ run.hi

/-- A Q-run containing `t` exists whenever `t` is a valid position of `q`. -/
theorem qRunAt_exists (ht : t < Tq) : Nonempty (QRunAt q Tq t) := by
  obtain ⟨r, hr, hlo, hhi⟩ :=
    (fullRunList_sound q Tq).exists_run_of_lt ht (Nat.zero_le t)
  exact ⟨{ run := r, mem := hr, lo_le_t := hlo, t_le_hi := hhi }⟩

/-- A canonical (noncomputable) choice of the Q-run containing `t`. -/
noncomputable def qRunAt (ht : t < Tq) : QRunAt q Tq t :=
  Classical.choice (qRunAt_exists (q := q) (Tq := Tq) (t := t) ht)

/-! ### Exact records for every causal K-position

The following list is independent of the Q-run choice.  It is the semantic
baseline: every `e < t` is stored exactly as `(lcsLen q k t e, e)`.
-/

/-- The causal part of a K-run, `[r.lo,r.hi] ∩ [0,t)`, as a list of
endpoints. -/
def causalEndpoints (t : Nat) (r : Run k Tk) : List Nat :=
  (List.range t).filter (fun e => decide (r.lo ≤ e ∧ e ≤ r.hi))

theorem mem_causalEndpoints {r : Run k Tk} {e : Nat}
    (he : e < t) (hlo : r.lo ≤ e) (hhi : e ≤ r.hi) :
    e ∈ causalEndpoints t r := by
  unfold causalEndpoints
  rw [List.mem_filter]
  exact ⟨by rw [List.mem_range]; exact he, by simp [hlo, hhi]⟩

/-- Exact row records on the causal part of one K-run. -/
def exactPrefixRecords (q k : Nat → α) (t : Nat) (r : Run k Tk) :
    List CapacityRecord :=
  (causalEndpoints t r).map
    (fun e => ({ cap := lcsLen q k t e, endpoint := e } : CapacityRecord))

/-- All exact row records generated by the canonical K-run decomposition. -/
def fullEndpointRecords (q k : Nat → α) (Tk t : Nat) : List CapacityRecord :=
  ((fullRunList k Tk).map (fun r => exactPrefixRecords q k t r)).flatten

theorem mem_exactPrefixRecords {r : Run k Tk} {e : Nat}
    (he : e < t) (hlo : r.lo ≤ e) (hhi : e ≤ r.hi) :
    ({ cap := lcsLen q k t e, endpoint := e } : CapacityRecord) ∈
      exactPrefixRecords q k t r := by
  unfold exactPrefixRecords
  rw [List.mem_map]
  exact ⟨e, mem_causalEndpoints he hlo hhi, rfl⟩

theorem exactPrefixRecords_sound (r : Run k Tk) :
    ∀ rec, rec ∈ exactPrefixRecords q k t r →
      rec.endpoint < t ∧ rec.cap = lcsLen q k t rec.endpoint := by
  intro rec hrec
  unfold exactPrefixRecords at hrec
  rw [List.mem_map] at hrec
  obtain ⟨e, he, rfl⟩ := hrec
  unfold causalEndpoints at he
  rw [List.mem_filter] at he
  exact ⟨by rw [List.mem_range] at he; exact he.1, rfl⟩

/-- The exact records from all maximal K-runs cover every causal endpoint. -/
theorem fullEndpointRecords_complete (hTk : t ≤ Tk) :
    CompleteAt (fun e => lcsLen q k t e) t
      (fullEndpointRecords q k Tk t) := by
  constructor
  · intro rec hrec
    unfold fullEndpointRecords at hrec
    rw [List.mem_flatten] at hrec
    obtain ⟨block, hblock, hrec⟩ := hrec
    rw [List.mem_map] at hblock
    obtain ⟨r, _hr, rfl⟩ := hblock
    exact exactPrefixRecords_sound r rec hrec
  · intro e he
    have heTk : e < Tk := Nat.lt_of_lt_of_le he hTk
    obtain ⟨r, hr, hlo, hhi⟩ :=
      (fullRunList_sound k Tk).exists_run_of_lt heTk (Nat.zero_le e)
    refine ⟨{ cap := lcsLen q k t e, endpoint := e }, ?_, rfl⟩
    unfold fullEndpointRecords
    rw [List.mem_flatten]
    refine ⟨exactPrefixRecords q k t r, ?_, mem_exactPrefixRecords he hlo hhi⟩
    rw [List.mem_map]
    exact ⟨r, hr, rfl⟩

/-! ### Opposite-symbol zero records and an automatic mixed cover -/

/-- The same causal endpoints as `exactPrefixRecords`, but with capacity zero.
It is used only for runs whose symbol differs from the selected Q-run. -/
def zeroPrefixRecords (t : Nat) (r : Run k Tk) : List CapacityRecord :=
  (causalEndpoints t r).map
    (fun e => ({ cap := 0, endpoint := e } : CapacityRecord))

theorem mem_zeroPrefixRecords {r : Run k Tk} {e : Nat}
    (he : e < t) (hlo : r.lo ≤ e) (hhi : e ≤ r.hi) :
    ({ cap := 0, endpoint := e } : CapacityRecord) ∈ zeroPrefixRecords t r := by
  unfold zeroPrefixRecords
  rw [List.mem_map]
  exact ⟨e, mem_causalEndpoints he hlo hhi, rfl⟩

/-- A zero record is semantically exact for an opposite-symbol maximal run. -/
theorem zeroPrefixRecords_sound (Q : QRunAt q Tq t) (r : Run k Tk)
    (hne : Q.run.sym ≠ r.sym) :
    ∀ rec, rec ∈ zeroPrefixRecords t r →
      rec.endpoint < t ∧ rec.cap = lcsLen q k t rec.endpoint := by
  intro rec hrec
  unfold zeroPrefixRecords at hrec
  rw [List.mem_map] at hrec
  obtain ⟨e, he, rfl⟩ := hrec
  unfold causalEndpoints at he
  rw [List.mem_filter] at he
  simp only [decide_eq_true_eq] at he
  refine ⟨by rw [List.mem_range] at he; exact he.1, ?_⟩
  exact (run_rectangle_symbol_ne Q.run.maximal r.maximal hne
    Q.lo_le_t Q.t_le_hi he.2.1 he.2.2).symm

/-- A same-symbol run is usable as a genuine `RealRun` only when both run
starts are positive and the K-run ends before `t`. -/
def IsCausalReal (Q : QRunAt q Tq t) (r : Run k Tk) : Prop :=
  0 < Q.run.lo ∧ 0 < r.lo ∧ Q.run.sym = r.sym ∧ r.hi < t

instance (Q : QRunAt q Tq t) (r : Run k Tk) : Decidable (IsCausalReal Q r) := by
  unfold IsCausalReal
  infer_instance

/-- Convert an eligible pair of maximal runs into a `RealRun`. -/
def realRunOf (Q : QRunAt q Tq t) (r : Run k Tk)
    (h : IsCausalReal Q r) : RealRun q k Tq Tk t :=
  { a := Q.run.lo
    b := Q.run.hi
    c := r.lo
    d := r.hi
    symQ := Q.run.sym
    symK := r.sym
    hQ := Q.run.maximal
    hK := r.maximal
    heq := h.2.2.1
    ha := h.1
    hc := h.2.1
    hcd := r.nonempty
    ht := Q.lo_le_t
    htb := Q.t_le_hi }

/-- The exact endpoint block contributed by one maximal K-run.  Eligible
same-symbol runs use the exact records of a real rectangle; opposite-symbol
runs use explicit zero records; all remaining runs use exact fallback records. -/
def endpointBlock (Q : QRunAt q Tq t) (r : Run k Tk) : List CapacityRecord :=
  if h : IsCausalReal Q r then
    (realRunOf Q r h).endpointRecords
  else if _hne : Q.run.sym ≠ r.sym then
    zeroPrefixRecords t r
  else
    exactPrefixRecords q k t r

/-- The compressed record block corresponding to `endpointBlock`.  The
ordinary/spike compression is used only in the genuine-real case. -/
def capacityBlock (Q : QRunAt q Tq t) (r : Run k Tk) : List CapacityRecord :=
  if h : IsCausalReal Q r then
    (realRunOf Q r h).capacityRecords
  else if _hne : Q.run.sym ≠ r.sym then
    zeroPrefixRecords t r
  else
    exactPrefixRecords q k t r

/-- The full endpoint-record cover generated automatically from `fullRunList`. -/
def automaticEndpointRecords (q k : Nat → α) (Tq Tk t : Nat)
    (Q : QRunAt q Tq t) : List CapacityRecord :=
  ((fullRunList k Tk).map (endpointBlock Q)).flatten

/-- The mixed compressed cover: real runs use ordinary/spike records, opposite
runs use zero records, and boundary fallbacks stay exact. -/
def automaticCapacityRecords (q k : Nat → α) (Tq Tk t : Nat)
    (Q : QRunAt q Tq t) : List CapacityRecord :=
  ((fullRunList k Tk).map (capacityBlock Q)).flatten

/-- Every endpoint in a block is semantically represented. -/
theorem endpointBlock_sound (Q : QRunAt q Tq t) (r : Run k Tk) :
    ∀ rec, rec ∈ endpointBlock Q r →
      rec.endpoint < t ∧ rec.cap = lcsLen q k t rec.endpoint := by
  intro rec hrec
  unfold endpointBlock at hrec
  by_cases hreal : IsCausalReal Q r
  · simp only [dif_pos hreal] at hrec
    exact (realRunOf Q r hreal).endpointRecords_sound_of_d_lt hreal.2.2.2 rec hrec
  · simp only [dif_neg hreal] at hrec
    by_cases hne : Q.run.sym ≠ r.sym
    · simp only [dif_pos hne] at hrec
      exact zeroPrefixRecords_sound Q r hne rec hrec
    · simp only [dif_neg hne] at hrec
      exact exactPrefixRecords_sound r rec hrec

/-- Every causal endpoint lies in the automatic endpoint cover, provided the
K-run decomposition reaches at least to `t`. -/
theorem automaticEndpointRecords_complete (Q : QRunAt q Tq t) (hTk : t ≤ Tk) :
    CompleteAt (fun e => lcsLen q k t e) t
      (automaticEndpointRecords q k Tq Tk t Q) := by
  constructor
  · intro rec hrec
    unfold automaticEndpointRecords at hrec
    rw [List.mem_flatten] at hrec
    obtain ⟨block, hblock, hrec⟩ := hrec
    rw [List.mem_map] at hblock
    obtain ⟨r, _hr, rfl⟩ := hblock
    exact endpointBlock_sound Q r rec hrec
  · intro e he
    have heTk : e < Tk := Nat.lt_of_lt_of_le he hTk
    obtain ⟨r, hr, hlo, hhi⟩ :=
      (fullRunList_sound k Tk).exists_run_of_lt heTk (Nat.zero_le e)
    by_cases hreal : IsCausalReal Q r
    · refine ⟨{ cap := lcsLen q k t e, endpoint := e }, ?_, rfl⟩
      unfold automaticEndpointRecords
      rw [List.mem_flatten]
      refine ⟨endpointBlock Q r, ?_, ?_⟩
      · rw [List.mem_map]
        exact ⟨r, hr, rfl⟩
      · rw [endpointBlock, dif_pos hreal]
        exact RealRun.mem_endpointRecords hlo hhi
    · by_cases hne : Q.run.sym ≠ r.sym
      · refine ⟨{ cap := 0, endpoint := e }, ?_, rfl⟩
        unfold automaticEndpointRecords
        rw [List.mem_flatten]
        refine ⟨endpointBlock Q r, ?_, ?_⟩
        · rw [List.mem_map]
          exact ⟨r, hr, rfl⟩
        · rw [endpointBlock, dif_neg hreal, dif_pos hne]
          exact mem_zeroPrefixRecords he hlo hhi
      · refine ⟨{ cap := lcsLen q k t e, endpoint := e }, ?_, rfl⟩
        unfold automaticEndpointRecords
        rw [List.mem_flatten]
        refine ⟨endpointBlock Q r, ?_, ?_⟩
        · rw [List.mem_map]
          exact ⟨r, hr, rfl⟩
        · rw [endpointBlock, dif_neg hreal, dif_neg hne]
          exact mem_exactPrefixRecords he hlo hhi

/-! ### Compressed and exact block semantics -/

/-- `foldr max` over an appended endpoint list. -/
theorem foldr_max_append (l₁ l₂ : List Int) :
    (l₁ ++ l₂).foldr max (-1) =
      max (l₁.foldr max (-1)) (l₂.foldr max (-1)) := by
  induction l₁ with
  | nil =>
      simp [Int.max_eq_right (CutArith.neg_one_le_foldr_max l₂)]
  | cons x xs ih =>
      rw [List.cons_append, List.foldr_cons, ih, List.foldr_cons]
      rw [Int.max_assoc]

/-- The latest eligible endpoint is compatible with list append. -/
theorem latestAt_append (rs rs' : List CapacityRecord) (lam : Nat) :
    latestAt (rs ++ rs') lam = max (latestAt rs lam) (latestAt rs' lam) := by
  unfold latestAt eligible
  rw [List.filter_append, List.map_append, foldr_max_append]

/-- The maximum capacity is compatible with list append. -/
theorem maxCap_append (rs rs' : List CapacityRecord) :
    maxCap (rs ++ rs') = max (maxCap rs) (maxCap rs') := by
  induction rs with
  | nil => simp [maxCap]
  | cons r rs ih => simp [maxCap, ih, Nat.max_assoc]

/-- Pointwise equality of block latest-endpoint semantics lifts through a
mapped/flattened list of blocks. -/
theorem latestAt_flatten_map_eq {β : Type} {as : List β}
    {f g : β → List CapacityRecord}
    (h : ∀ a, a ∈ as → ∀ lam, latestAt (f a) lam = latestAt (g a) lam) :
    ∀ lam, latestAt (as.map f).flatten lam = latestAt (as.map g).flatten lam := by
  induction as with
  | nil => intro lam; simp [latestAt]
  | cons a as ih =>
      intro lam
      simp only [List.map_cons, List.flatten_cons]
      rw [latestAt_append, latestAt_append]
      rw [h a (by simp) lam]
      rw [ih (fun b hb => h b (by simp [hb]))]

/-- Pointwise equality of block maxima lifts through a mapped/flattened list of
blocks. -/
theorem maxCap_flatten_map_eq {β : Type} {as : List β}
    {f g : β → List CapacityRecord}
    (h : ∀ a, a ∈ as → maxCap (f a) = maxCap (g a)) :
    maxCap (as.map f).flatten = maxCap (as.map g).flatten := by
  induction as with
  | nil => simp [maxCap]
  | cons a as ih =>
      simp only [List.map_cons, List.flatten_cons]
      rw [maxCap_append, maxCap_append]
      rw [h a (by simp)]
      rw [ih (fun b hb => h b (by simp [hb]))]

/-- The ordinary/spike compression of one automatically classified block has
the same threshold-latest endpoint semantics as its exact block. -/
theorem capacityBlock_latestAt_eq_endpointBlock
    (Q : QRunAt q Tq t) (r : Run k Tk) (lam : Nat) :
    latestAt (capacityBlock Q r) lam = latestAt (endpointBlock Q r) lam := by
  unfold capacityBlock endpointBlock
  by_cases hreal : IsCausalReal Q r
  · rw [dif_pos hreal, dif_pos hreal]
    exact (realRunOf Q r hreal).latestAt_capacityRecords_eq_endpointRecords lam
  · rw [dif_neg hreal, dif_neg hreal]

/-- The ordinary/spike compression of one automatically classified block has
the same maximum capacity as its exact block. -/
theorem capacityBlock_maxCap_eq_endpointBlock
    (Q : QRunAt q Tq t) (r : Run k Tk) :
    maxCap (capacityBlock Q r) = maxCap (endpointBlock Q r) := by
  unfold capacityBlock endpointBlock
  by_cases hreal : IsCausalReal Q r
  · rw [dif_pos hreal, dif_pos hreal]
    have h := CapacityConcrete.maxCap_multiCapacityRecords_eq_multiEndpointRecords
      [realRunOf Q r hreal]
    simpa [multiCapacityRecords, multiEndpointRecords] using h
  · rw [dif_neg hreal, dif_neg hreal]

/-- Automatic compressed records preserve the latest eligible endpoint of the
automatic exact cover at every threshold. -/
theorem automaticCapacityRecords_latestAt_eq_endpointRecords
    (Q : QRunAt q Tq t) (lam : Nat) :
    latestAt (automaticCapacityRecords q k Tq Tk t Q) lam =
      latestAt (automaticEndpointRecords q k Tq Tk t Q) lam := by
  unfold automaticCapacityRecords automaticEndpointRecords
  exact latestAt_flatten_map_eq
    (as := fullRunList k Tk)
    (f := capacityBlock Q) (g := endpointBlock Q)
    (fun r _hr => capacityBlock_latestAt_eq_endpointBlock Q r) lam

/-- Automatic compressed records preserve the maximum capacity of the automatic
exact cover. -/
theorem automaticCapacityRecords_maxCap_eq_endpointRecords
    (Q : QRunAt q Tq t) :
    maxCap (automaticCapacityRecords q k Tq Tk t Q) =
      maxCap (automaticEndpointRecords q k Tq Tk t Q) := by
  unfold automaticCapacityRecords automaticEndpointRecords
  exact maxCap_flatten_map_eq
    (as := fullRunList k Tk)
    (f := capacityBlock Q) (g := endpointBlock Q)
    (fun r _hr => capacityBlock_maxCap_eq_endpointBlock Q r)

/-! ### The genuine `RealRun` sub-cover -/

/-- The real rectangles extracted from the maximal K-runs. -/
def automaticRealRuns (q k : Nat → α) (Tq Tk t : Nat)
    (Q : QRunAt q Tq t) : List (RealRun q k Tq Tk t) :=
  (fullRunList k Tk).filterMap (fun r =>
    if h : IsCausalReal Q r then some (realRunOf Q r h) else none)

/-- Explicit residual extraction hypothesis: every causal endpoint is supplied
by a K-run which is eligible for a genuine `RealRun`.  This is the precise
hypothesis under which the automatically extracted real sub-list covers the
whole row; it intentionally excludes opposite-symbol and boundary fallback
endpoints. -/
def RealRunExtraction (q : Nat → α) (k : Nat → α) (Tq Tk t : Nat)
    (Q : QRunAt q Tq t) : Prop :=
  ∀ e, e < t →
    ∃ r, r ∈ fullRunList k Tk ∧ r.lo ≤ e ∧ e ≤ r.hi ∧ IsCausalReal Q r

theorem mem_automaticRealRuns (Q : QRunAt q Tq t)
    {R : RealRun q k Tq Tk t} :
    R ∈ automaticRealRuns q k Tq Tk t Q ↔
      ∃ r, r ∈ fullRunList k Tk ∧
        ∃ h : IsCausalReal Q r, R = realRunOf Q r h := by
  unfold automaticRealRuns
  rw [List.mem_filterMap]
  constructor
  · rintro ⟨r, hr, hopt⟩
    by_cases h : IsCausalReal Q r
    · rw [dif_pos h] at hopt
      injection hopt with hEq
      exact ⟨r, hr, h, hEq.symm⟩
    · rw [dif_neg h] at hopt
      simp at hopt
  · rintro ⟨r, hr, h, rfl⟩
    exact ⟨r, hr, by simp [h]⟩

theorem automaticRealRuns_ends_before (Q : QRunAt q Tq t) :
    ∀ R : RealRun q k Tq Tk t, R ∈ automaticRealRuns q k Tq Tk t Q → R.d < t := by
  intro R hR
  rw [mem_automaticRealRuns] at hR
  obtain ⟨r, _hr, h, rfl⟩ := hR
  exact h.2.2.2

theorem realRunExtraction_of_runwise
    (Q : QRunAt q Tq t) (hTk : t ≤ Tk)
    (hruns : ∀ r, r ∈ fullRunList k Tk → r.lo < t → IsCausalReal Q r) :
    RealRunExtraction q k Tq Tk t Q := by
  intro e he
  have heTk : e < Tk := Nat.lt_of_lt_of_le he hTk
  obtain ⟨r, hr, hlo, hhi⟩ :=
    (fullRunList_sound k Tk).exists_run_of_lt heTk (Nat.zero_le e)
  exact ⟨r, hr, hlo, hhi, hruns r hr (by omega)⟩

theorem automaticRealRuns_rowCovered_of_extraction
    (Q : QRunAt q Tq t) (h : RealRunExtraction q k Tq Tk t Q) :
    CapacityConcrete.RowCovered (automaticRealRuns q k Tq Tk t Q) := by
  refine ⟨automaticRealRuns_ends_before Q, ?_⟩
  intro e he
  obtain ⟨r, hr, hlo, hhi, hreal⟩ := h e he
  refine ⟨realRunOf Q r hreal, ?_, ?_, ?_⟩
  · rw [mem_automaticRealRuns]
    exact ⟨r, hr, hreal, rfl⟩
  · exact hlo
  · exact hhi

/-- If the automatically extracted real rectangles already cover every causal
endpoint, they discharge the existing `RowCovered` boundary.  This is the
honest residual extraction hypothesis: opposite-symbol or boundary endpoints
cannot be made into `RealRun`s without changing the run hypothesis. -/
theorem automaticRealRuns_rowCovered (Q : QRunAt q Tq t)
    (hcover : ∀ e, e < t →
      ∃ R : RealRun q k Tq Tk t,
        R ∈ automaticRealRuns q k Tq Tk t Q ∧ R.c ≤ e ∧ e ≤ R.d) :
    CapacityConcrete.RowCovered (automaticRealRuns q k Tq Tk t Q) :=
  ⟨automaticRealRuns_ends_before Q, hcover⟩

/-- The exact endpoint cover of a genuine real sub-cover. -/
theorem automaticRealRuns_completeAt
    (Q : QRunAt q Tq t)
    (hcover : ∀ e, e < t →
      ∃ R : RealRun q k Tq Tk t,
        R ∈ automaticRealRuns q k Tq Tk t Q ∧ R.c ≤ e ∧ e ≤ R.d) :
    CompleteAt (fun e => lcsLen q k t e) t
      (multiEndpointRecords (automaticRealRuns q k Tq Tk t Q)) :=
  CapacityConcrete.completeAt_multiEndpointRecords_of_rowCovered
    (automaticRealRuns_rowCovered Q hcover)

/-- Consequently the compressed multi-run records have the same Q-cut
threshold semantics as the dense row, under the same explicit coverage
hypothesis. -/
theorem automaticRealRuns_qcut
    (Q : QRunAt q Tq t)
    (hcover : ∀ e, e < t →
      ∃ R : RealRun q k Tq Tk t,
        R ∈ automaticRealRuns q k Tq Tk t Q ∧ R.c ≤ e ∧ e ≤ R.d)
    {u : Nat} (ht : 0 < t) (hu : u ≤ t) :
    QCut.qcutClosed (fun e => (lcsLen q k t e : Int)) t u =
      CapacityMultiRun.thresholdRoute
        (multiCapacityRecords (automaticRealRuns q k Tq Tk t Q))
        (min (CapacityMultiRun.maxCap
          (multiCapacityRecords (automaticRealRuns q k Tq Tk t Q))) (t - u)) :=
  CapacityConcrete.qcutClosed_eq_thresholdRoute_multiCapacityRecords_of_rowCovered
    (automaticRealRuns_rowCovered Q hcover) ht hu

/-! ### Automatic Q-cut endpoint bridge -/

/-- The automatically constructed exact cover gives the Q-cut bridge without
any maximality assumption beyond `t ≤ Tk`. -/
theorem automaticEndpointRecords_qcut
    (Q : QRunAt q Tq t) (hTk : t ≤ Tk)
    {u : Nat} (ht : 0 < t) (hu : u ≤ t) :
    QCut.qcutClosed (fun e => (lcsLen q k t e : Int)) t u =
      CapacityMultiRun.thresholdRoute
        (automaticEndpointRecords q k Tq Tk t Q)
        (min (CapacityMultiRun.maxCap (automaticEndpointRecords q k Tq Tk t Q)) (t - u)) :=
  CapacityMultiRun.qcutClosed_eq_thresholdRoute_of_complete
    (automaticEndpointRecords_complete Q hTk) ht hu

/-- The mixed compressed cover computes the same Q-cut route as the exact
automatic cover.  Opposite-symbol endpoints are explicit zero records; only
eligible same-symbol runs use the ordinary/spike compression. -/
theorem automaticCapacityRecords_qcut
    (Q : QRunAt q Tq t) (hTk : t ≤ Tk)
    {u : Nat} (ht : 0 < t) (hu : u ≤ t) :
    QCut.qcutClosed (fun e => (lcsLen q k t e : Int)) t u =
      CapacityMultiRun.thresholdRoute
        (automaticCapacityRecords q k Tq Tk t Q)
        (min (CapacityMultiRun.maxCap
          (automaticCapacityRecords q k Tq Tk t Q)) (t - u)) := by
  rw [automaticEndpointRecords_qcut Q hTk ht hu]
  unfold CapacityMultiRun.thresholdRoute
  rw [← automaticCapacityRecords_maxCap_eq_endpointRecords Q]
  rw [← automaticCapacityRecords_latestAt_eq_endpointRecords Q]
/-- Alias with the task-facing name for the exact automatic completeness theorem. -/
theorem automaticCompleteAt (Q : QRunAt q Tq t) (hTk : t ≤ Tk) :
    CompleteAt (fun e => lcsLen q k t e) t
      (automaticEndpointRecords q k Tq Tk t Q) :=
  automaticEndpointRecords_complete Q hTk

/-- Automatically extract the `RealRun` cover from a runwise eligibility
hypothesis and `t ≤ Tk`. -/
theorem automaticRowCovered_of_runwise
    (Q : QRunAt q Tq t) (hTk : t ≤ Tk)
    (hruns : ∀ r, r ∈ fullRunList k Tk → r.lo < t → IsCausalReal Q r) :
    CapacityConcrete.RowCovered (automaticRealRuns q k Tq Tk t Q) :=
  automaticRealRuns_rowCovered_of_extraction Q
    (realRunExtraction_of_runwise Q hTk hruns)

/-- Alias for the extracted `RealRun` cover under the explicit extraction
hypothesis. -/
theorem automaticRowCovered_of_extraction
    (Q : QRunAt q Tq t) (h : RealRunExtraction q k Tq Tk t Q) :
    CapacityConcrete.RowCovered (automaticRealRuns q k Tq Tk t Q) :=
  automaticRealRuns_rowCovered_of_extraction Q h

end CapacityAutomaticRunCover
