import CapacityMultiRun

/-!
## Concrete string-run completeness for capacity/M0

This file connects the string-level equal-symbol rectangle theorem to the
multi-run capacity-record layer.

Two record views are kept separate:

* `endpointRecords R` contains the exact row value `(row R e, e)` for every
  endpoint `e` in the K run `[R.c, R.d]`.
* `capacityRecords R` is the ordinary/spike compression from §7.1.

The first view makes `CapacityMultiRun.CompleteAt` a consequence of an explicit
row-cover hypothesis.  The second view is proved to have the same
threshold-latest endpoint semantics, so the Q-cut bridge can also be stated for
the compressed multi-run records.
-/

open Route
open Capacity
open Lcs
open CapacityMultiRun
open RunRect

namespace CapacityConcrete

set_option linter.unusedSectionVars false

variable {α : Type} [DecidableEq α]

private theorem rle_pair_nat {l l' e e' : Nat} (hl : l ≤ l') (he : e ≤ e') :
    rle (⟨(l : Int), (e : Int)⟩ : Route)
      (⟨(l' : Int), (e' : Int)⟩ : Route) := by
  unfold rle
  dsimp only
  by_cases h : l = l'
  · right
    exact ⟨by omega, by exact_mod_cast he⟩
  · left
    omega

/-- A genuine same-symbol rectangle of a fixed output row `t`.

The fields `hQ` and `hK` witness maximal constant runs of the two strings.
The condition `heq` is the equal-symbol case consumed by the run-rectangle
capacity theorem. -/
structure RealRun (q k : Nat → α) (Tq Tk t : Nat) where
  a : Nat
  b : Nat
  c : Nat
  d : Nat
  symQ : α
  symK : α
  hQ : ConstRun q Tq a b symQ
  hK : ConstRun k Tk c d symK
  heq : symQ = symK
  ha : 0 < a
  hc : 0 < c
  hcd : c ≤ d
  ht : a ≤ t
  htb : t ≤ b

namespace RealRun

variable {q k : Nat → α} {Tq Tk t : Nat}

/-- The concrete ROSA row at the fixed output position `t`. -/
def row (_R : RealRun q k Tq Tk t) (e : Nat) : Nat :=
  lcsLen q k t e

/-- Q-run offset consumed by the rectangle theorem. -/
def x (R : RealRun q k Tq Tk t) : Nat :=
  t - R.a + 1

/-- Diagonal context increment at the left edge of the rectangle. -/
def gamma (R : RealRun q k Tq Tk t) : Nat :=
  lcsLen q k (R.a - 1) (R.c - 1)

/-- The diagonal spike endpoint in the K run. -/
def spikeEndpoint (R : RealRun q k Tq Tk t) : Nat :=
  Capacity.spikeEndpoint R.c R.x

theorem x_pos (R : RealRun q k Tq Tk t) : 0 < R.x := by
  unfold x
  omega

theorem ordinaryCap_pos (R : RealRun q k Tq Tk t) :
    0 < Capacity.ordinaryCap R.x (R.d - R.c + 1) := by
  unfold Capacity.ordinaryCap
  rw [Nat.lt_min]
  constructor
  · exact R.x_pos
  · omega

theorem spikeCap_pos (R : RealRun q k Tq Tk t) :
    0 < Capacity.spikeCap R.x R.gamma := by
  unfold Capacity.spikeCap
  exact Nat.lt_of_lt_of_le R.x_pos (Nat.le_add_right _ _)

theorem spikeEndpoint_ge_c (R : RealRun q k Tq Tk t) :
    R.c ≤ R.spikeEndpoint := by
  unfold spikeEndpoint Capacity.spikeEndpoint x
  omega

theorem spikeEndpoint_eq_iff (R : RealRun q k Tq Tk t) :
    R.spikeEndpoint ≤ R.d ↔ R.c + R.x - 1 ≤ R.d := by
  rfl

theorem row_spikeEndpoint (R : RealRun q k Tq Tk t)
    (hp : R.spikeEndpoint ≤ R.d) :
    R.row R.spikeEndpoint = Capacity.spikeCap R.x R.gamma := by
  have hsp := RunHook.rspRow_of_rectangle R.hQ R.hK R.heq R.ha R.hc R.ht R.htb
  have hy : R.spikeEndpoint - R.c + 1 = R.x := by
    unfold spikeEndpoint Capacity.spikeEndpoint x
    omega
  change lcsLen q k t R.spikeEndpoint = R.x + R.gamma
  rw [hsp.spike R.spikeEndpoint R.spikeEndpoint_ge_c hp hy]
  rfl

/-- The ordinary record `(min x n, d)` generated by the real rectangle. -/
def ordinaryRecord (R : RealRun q k Tq Tk t) : CapacityRecord :=
  { cap := Capacity.ordinaryCap R.x (R.d - R.c + 1)
    endpoint := R.d }

/-- The spike record `(x+gamma, c+x-1)`, present only when its endpoint lies in
the K run. -/
def spikeRecord? (R : RealRun q k Tq Tk t) : Option CapacityRecord :=
  if _hp : R.spikeEndpoint ≤ R.d then
    some { cap := Capacity.spikeCap R.x R.gamma
           endpoint := R.spikeEndpoint }
  else
    none

/-- The ordinary/spike compressed record list from the concrete rectangle. -/
def capacityRecords (R : RealRun q k Tq Tk t) : List CapacityRecord :=
  CapacityMultiRun.rectangleRecords R.c R.d R.x R.gamma

/-- All exact endpoint records `(row e, e)` in the K run. -/
def endpointRecords (R : RealRun q k Tq Tk t) : List CapacityRecord :=
  (List.range (R.d - R.c + 1)).map
    (fun i => { cap := R.row (R.c + i), endpoint := R.c + i })

theorem mem_endpointRecords {R : RealRun q k Tq Tk t} {e : Nat}
    (hce : R.c ≤ e) (hed : e ≤ R.d) :
    ({ cap := R.row e, endpoint := e } : CapacityRecord) ∈ R.endpointRecords := by
  unfold endpointRecords
  rw [List.mem_map]
  refine ⟨e - R.c, ?_, ?_⟩
  · rw [List.mem_range]
    omega
  · have hsub : R.c + (e - R.c) = e := by omega
    simp [hsub]

/-- Exact endpoint records generated by one run are causal once the run ends
before the row position `t`. -/
theorem endpointRecords_sound_of_d_lt (R : RealRun q k Tq Tk t)
    (hdt : R.d < t) :
    ∀ r, r ∈ R.endpointRecords → r.endpoint < t ∧ r.cap = R.row r.endpoint := by
  intro r hr
  unfold endpointRecords at hr
  rw [List.mem_map] at hr
  obtain ⟨i, hi, rfl⟩ := hr
  rw [List.mem_range] at hi
  constructor
  · change R.c + i < t
    have hcd := R.hcd
    omega
  · rfl

/-- Exact endpoint records generated by one run cover its whole K interval. -/
theorem endpointRecords_covers_interval (R : RealRun q k Tq Tk t) :
    ∀ e, R.c ≤ e → e ≤ R.d →
      ∃ r, r ∈ R.endpointRecords ∧ r.endpoint = e := by
  intro e hce hed
  refine ⟨{ cap := R.row e, endpoint := e }, mem_endpointRecords hce hed, rfl⟩

/-- The exact capacity record for a concrete endpoint. -/
def exactRecord (R : RealRun q k Tq Tk t) (e : Nat) : CapacityRecord :=
  { cap := R.row e, endpoint := e }

theorem exactRecord_toRoute_eq (R : RealRun q k Tq Tk t) (e : Nat) :
    (R.exactRecord e).toRoute =
      CutArith.mk ((R.row e : Nat) : Int) (e : Int) := by
  rfl

/-- The ordinary record's capacity is a lower bound for the exact row value at
its endpoint `d`. -/
theorem ordinaryRecord_cap_le_row_d (R : RealRun q k Tq Tk t) :
    R.ordinaryRecord.cap ≤ R.row R.d := by
  have hle := (Capacity.run_capacity_latest_endpoint R.hQ R.hK R.heq R.ha R.hc
    R.hcd R.ht R.htb (lam := Capacity.ordinaryCap R.x (R.d - R.c + 1))).1
      (Nat.le_refl _)
  simpa [ordinaryRecord, row] using hle

/-- The ordinary record is never above the exact route at `d`. -/
theorem ordinaryRecord_toRoute_le_exact_d (R : RealRun q k Tq Tk t) :
    rle R.ordinaryRecord.toRoute (R.exactRecord R.d).toRoute := by
  have hcap := R.ordinaryRecord_cap_le_row_d
  by_cases hzero : R.ordinaryRecord.cap = 0
  · rw [CapacityRecord.toRoute_eq_unmatched_of_zero hzero]
    exact valid_rle_unmatched _ (CapacityRecord.valid_toRoute _)
  · have hpos : 0 < R.ordinaryRecord.cap := Nat.pos_of_ne_zero hzero
    have hrowpos : 0 < R.row R.d := Nat.lt_of_lt_of_le hpos hcap
    rw [CapacityRecord.toRoute_eq_of_pos hpos]
    unfold exactRecord
    rw [CapacityRecord.toRoute_eq_of_pos hrowpos]
    exact rle_pair_nat hcap (Nat.le_refl R.d)

/-- A feasible spike record is exactly the row value at its endpoint. -/
theorem spikeRecord_toRoute_eq_exact_of_feasible (R : RealRun q k Tq Tk t)
    (hp : R.spikeEndpoint ≤ R.d) :
    (CapacityRecord.toRoute
      { cap := Capacity.spikeCap R.x R.gamma, endpoint := R.spikeEndpoint }) =
      (R.exactRecord R.spikeEndpoint).toRoute := by
  have hrowpos : 0 < R.row R.spikeEndpoint := by
    rw [R.row_spikeEndpoint hp]
    exact R.spikeCap_pos
  rw [CapacityRecord.toRoute_eq_of_pos R.spikeCap_pos]
  unfold exactRecord
  rw [CapacityRecord.toRoute_eq_of_pos hrowpos]
  simp [R.row_spikeEndpoint hp]

/-- The ordinary/spike compression has exactly the same `rmaxList` as all
exact endpoint routes of the run. -/
theorem capacityRecords_rmax_eq_endpointRecords (R : RealRun q k Tq Tk t) :
    rmaxList (R.capacityRecords.map CapacityRecord.toRoute) =
      rmaxList (R.endpointRecords.map CapacityRecord.toRoute) := by
  have hrec := CapacityMultiRun.rectangleRecords_rmax_eq_two_records
    (c := R.c) (d := R.d) (x := R.x) (gamma := R.gamma) R.hcd R.x_pos
  have htwo := Capacity.run_capacity_two_records_sufficient
    R.hQ R.hK R.heq R.ha R.hc R.hcd R.ht R.htb
  calc
    rmaxList (R.capacityRecords.map CapacityRecord.toRoute)
        = rmax (Capacity.ordinaryRecord R.c R.d R.x)
            (Capacity.spikeRecord R.c R.d R.x R.gamma) := by
          simpa [capacityRecords] using hrec
    _ = rmaxList (Capacity.rspEndpointRoutes (fun e => lcsLen q k t e) R.c R.d) := by
          simpa [x, gamma, row] using htwo.symm
    _ = rmaxList (R.endpointRecords.map CapacityRecord.toRoute) := by
          congr 1
          simp only [endpointRecords, Capacity.rspEndpointRoutes, List.map_map,
            Function.comp_def]
          apply List.map_congr_left
          intro i _hi
          simp [CapacityRecord.toRoute, row]

/-- A compressed capacity record always points below a genuine endpoint whose
exact row value reaches the threshold. -/
theorem capacity_record_yields_exact_endpoint (R : RealRun q k Tq Tk t)
    {lam : Nat} {r : CapacityRecord} (hr : r ∈ R.capacityRecords)
    (hle : lam ≤ r.cap) :
    ∃ e, R.c ≤ e ∧ e ≤ R.d ∧ r.endpoint ≤ e ∧ lam ≤ R.row e := by
  unfold capacityRecords CapacityMultiRun.rectangleRecords at hr
  by_cases hp : R.spikeEndpoint ≤ R.d
  · have hp' : Capacity.spikeEndpoint R.c R.x ≤ R.d := by
      simpa [spikeEndpoint] using hp
    rw [if_pos hp'] at hr
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hr
    rcases hr with h | h
    · subst r
      refine ⟨R.d, R.hcd, Nat.le_refl _, Nat.le_refl _, ?_⟩
      exact Nat.le_trans hle R.ordinaryRecord_cap_le_row_d
    · subst r
      refine ⟨R.spikeEndpoint, R.spikeEndpoint_ge_c, hp, Nat.le_refl _, ?_⟩
      rw [R.row_spikeEndpoint hp]
      simpa [Capacity.spikeCap] using hle
  · have hp' : ¬ Capacity.spikeEndpoint R.c R.x ≤ R.d := by
      simpa [spikeEndpoint] using hp
    rw [if_neg hp'] at hr
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hr
    subst r
    refine ⟨R.d, R.hcd, Nat.le_refl _, Nat.le_refl _, ?_⟩
    exact Nat.le_trans hle R.ordinaryRecord_cap_le_row_d

/-- A genuine endpoint reaching the threshold is represented by a compressed
record at or after it. -/
theorem exact_endpoint_yields_capacity_record (R : RealRun q k Tq Tk t)
    {lam e : Nat} (hce : R.c ≤ e) (hed : e ≤ R.d)
    (hle : lam ≤ R.row e) :
    ∃ r, r ∈ R.capacityRecords ∧ lam ≤ r.cap ∧ e ≤ r.endpoint := by
  cases hmax : Capacity.maxEndpoint? q k R.a R.b R.c R.d t lam with
  | none =>
      have hfail := Capacity.run_capacity_none_endpoint_fails R.hQ R.hK R.heq
        R.ha R.hc R.hcd R.ht R.htb hmax
      exact False.elim (hfail e hce hed hle)
  | some E =>
      have hEmax := Capacity.run_capacity_some_endpoint_is_max R.hQ R.hK R.heq
        R.ha R.hc R.hcd R.ht R.htb hmax
      have heE : e ≤ E := hEmax.2 e ⟨hce, hed, hle⟩
      have hbranch := (Capacity.run_capacity_maxEndpoint?_eq_some_iff
        (q := q) (k := k) (a := R.a) (b := R.b) (c := R.c) (d := R.d)
        (t := t) (lam := lam) (e := E)).1 hmax
      rcases hbranch with ⟨hEd, hord⟩ | ⟨hEp, _hnot, hspikefeas, hspike⟩
      · subst E
        refine ⟨R.ordinaryRecord, ?_, hord, heE⟩
        simp [capacityRecords, CapacityMultiRun.rectangleRecords, ordinaryRecord]
      · subst E
        refine ⟨{ cap := Capacity.spikeCap R.x R.gamma,
                   endpoint := R.spikeEndpoint }, ?_, hspike, heE⟩
        unfold capacityRecords CapacityMultiRun.rectangleRecords
        have hp' : Capacity.spikeEndpoint R.c R.x ≤ R.d := by
          simpa [spikeEndpoint, x] using hspikefeas
        rw [if_pos hp']
        simp [spikeEndpoint]

/-- At every threshold, the compressed ordinary/spike records and the exact
endpoint records have the same latest reaching endpoint. -/
theorem latestAt_capacityRecords_eq_endpointRecords (R : RealRun q k Tq Tk t)
    (lam : Nat) :
    CapacityMultiRun.latestAt R.capacityRecords lam =
      CapacityMultiRun.latestAt R.endpointRecords lam := by
  apply Int.le_antisymm
  · unfold CapacityMultiRun.latestAt
    apply CapacityMultiRun.foldr_max_le
    · exact CutArith.neg_one_le_foldr_max _
    · intro x hx
      rw [List.mem_map] at hx
      obtain ⟨r, hrElig, rfl⟩ := hx
      unfold CapacityMultiRun.eligible at hrElig
      rw [List.mem_filter] at hrElig
      obtain ⟨hr, hp⟩ := hrElig
      simp only [decide_eq_true_eq] at hp
      obtain ⟨e, hce, hed, hre, hleRow⟩ :=
        R.capacity_record_yields_exact_endpoint hr hp
      have hmem : ({ cap := R.row e, endpoint := e } : CapacityRecord) ∈
          R.endpointRecords := RealRun.mem_endpointRecords hce hed
      have hlam : lam ≤ ({ cap := R.row e, endpoint := e } : CapacityRecord).cap := hleRow
      exact Int.le_trans (by exact_mod_cast hre)
        (CapacityMultiRun.endpoint_le_latestAt hmem hlam)
  · unfold CapacityMultiRun.latestAt
    apply CapacityMultiRun.foldr_max_le
    · exact CutArith.neg_one_le_foldr_max _
    · intro x hx
      rw [List.mem_map] at hx
      obtain ⟨r, hrElig, rfl⟩ := hx
      unfold CapacityMultiRun.eligible at hrElig
      rw [List.mem_filter] at hrElig
      obtain ⟨hr, hp⟩ := hrElig
      simp only [decide_eq_true_eq] at hp
      unfold endpointRecords at hr
      rw [List.mem_map] at hr
      obtain ⟨i, hi, rfl⟩ := hr
      rw [List.mem_range] at hi
      have hce : R.c ≤ R.c + i := Nat.le_add_right _ _
      have hed : R.c + i ≤ R.d := by
        have hcd := R.hcd
        omega
      have hleRow : lam ≤ R.row (R.c + i) := by simpa using hp
      obtain ⟨s, hs, hlam, h_er⟩ :=
        R.exact_endpoint_yields_capacity_record hce hed hleRow
      exact Int.le_trans (by exact_mod_cast h_er)
        (CapacityMultiRun.endpoint_le_latestAt hs hlam)

end RealRun

variable {q k : Nat → α} {Tq Tk t : Nat}

/-- All exact endpoint records contributed by a list of concrete rectangles. -/
def multiEndpointRecords (runs : List (RealRun q k Tq Tk t)) :
    List CapacityRecord :=
  (runs.map RealRun.endpointRecords).flatten

/-- All compressed ordinary/spike records contributed by a list of concrete
rectangles. -/
def multiCapacityRecords (runs : List (RealRun q k Tq Tk t)) :
    List CapacityRecord :=
  (runs.map RealRun.capacityRecords).flatten

/-- Explicit row-cover boundary for a concrete run list.

Every run must end before the query position `t`, and every causal endpoint in
`[0,t)` must lie in at least one run interval.  Intervals may overlap. -/
def RowCovered (runs : List (RealRun q k Tq Tk t)) : Prop :=
  (∀ R, R ∈ runs → R.d < t) ∧
    (∀ e, e < t → ∃ R, R ∈ runs ∧ R.c ≤ e ∧ e ≤ R.d)

/-- A concrete run list covering the row discharges `CompleteAt` using the exact
endpoint records generated by each real rectangle. -/
theorem completeAt_multiEndpointRecords_of_rowCovered
    {runs : List (RealRun q k Tq Tk t)} (hcover : RowCovered runs) :
    CapacityMultiRun.CompleteAt (fun e => lcsLen q k t e) t
      (multiEndpointRecords runs) := by
  constructor
  · intro r hr
    unfold multiEndpointRecords at hr
    rw [List.mem_flatten] at hr
    obtain ⟨block, hblock, hrblock⟩ := hr
    rw [List.mem_map] at hblock
    obtain ⟨R, hR, rfl⟩ := hblock
    exact RealRun.endpointRecords_sound_of_d_lt R (hcover.1 R hR) r hrblock
  · intro e he
    obtain ⟨R, hR, hce, hed⟩ := hcover.2 e he
    refine ⟨{ cap := lcsLen q k t e, endpoint := e }, ?_, rfl⟩
    unfold multiEndpointRecords
    rw [List.mem_flatten]
    refine ⟨R.endpointRecords, ?_, RealRun.mem_endpointRecords hce hed⟩
    rw [List.mem_map]
    exact ⟨R, hR, rfl⟩

/-- The compressed multi-run records have the same latest reaching endpoint as
the exact multi-run endpoint records, for every threshold. -/
theorem latestAt_multiCapacityRecords_eq_multiEndpointRecords
    (runs : List (RealRun q k Tq Tk t)) (lam : Nat) :
    CapacityMultiRun.latestAt (multiCapacityRecords runs) lam =
      CapacityMultiRun.latestAt (multiEndpointRecords runs) lam := by
  apply Int.le_antisymm
  · unfold CapacityMultiRun.latestAt
    apply CapacityMultiRun.foldr_max_le
    · exact CutArith.neg_one_le_foldr_max _
    · intro x hx
      rw [List.mem_map] at hx
      obtain ⟨r, hrElig, rfl⟩ := hx
      unfold CapacityMultiRun.eligible at hrElig
      rw [List.mem_filter] at hrElig
      obtain ⟨hr, hp⟩ := hrElig
      simp only [decide_eq_true_eq] at hp
      unfold multiCapacityRecords at hr
      rw [List.mem_flatten] at hr
      obtain ⟨block, hblock, hrblock⟩ := hr
      rw [List.mem_map] at hblock
      obtain ⟨R, _hR, rfl⟩ := hblock
      obtain ⟨e, hce, hed, hre, hleRow⟩ :=
        R.capacity_record_yields_exact_endpoint hrblock hp
      have hmemBlock : R.endpointRecords ∈ runs.map RealRun.endpointRecords := by
        rw [List.mem_map]
        exact ⟨R, _hR, rfl⟩
      have hmem : ({ cap := R.row e, endpoint := e } : CapacityRecord) ∈
          multiEndpointRecords runs := by
        unfold multiEndpointRecords
        rw [List.mem_flatten]
        exact ⟨R.endpointRecords, hmemBlock, RealRun.mem_endpointRecords hce hed⟩
      have hlam : lam ≤ ({ cap := R.row e, endpoint := e } : CapacityRecord).cap := hleRow
      exact Int.le_trans (by exact_mod_cast hre)
        (CapacityMultiRun.endpoint_le_latestAt hmem hlam)
  · unfold CapacityMultiRun.latestAt
    apply CapacityMultiRun.foldr_max_le
    · exact CutArith.neg_one_le_foldr_max _
    · intro x hx
      rw [List.mem_map] at hx
      obtain ⟨r, hrElig, rfl⟩ := hx
      unfold CapacityMultiRun.eligible at hrElig
      rw [List.mem_filter] at hrElig
      obtain ⟨hr, hp⟩ := hrElig
      simp only [decide_eq_true_eq] at hp
      unfold multiEndpointRecords at hr
      rw [List.mem_flatten] at hr
      obtain ⟨block, hblock, hrblock⟩ := hr
      rw [List.mem_map] at hblock
      obtain ⟨R, _hR, rfl⟩ := hblock
      unfold RealRun.endpointRecords at hrblock
      rw [List.mem_map] at hrblock
      obtain ⟨i, hi, rfl⟩ := hrblock
      rw [List.mem_range] at hi
      have hce : R.c ≤ R.c + i := Nat.le_add_right _ _
      have hed : R.c + i ≤ R.d := by
        have hcd := R.hcd
        omega
      have hleRow : lam ≤ R.row (R.c + i) := by simpa using hp
      obtain ⟨s, hsRun, hlam, h_er⟩ :=
        R.exact_endpoint_yields_capacity_record hce hed hleRow
      have hmemBlock : R.capacityRecords ∈ runs.map RealRun.capacityRecords := by
        rw [List.mem_map]
        exact ⟨R, _hR, rfl⟩
      have hmem : s ∈ multiCapacityRecords runs := by
        unfold multiCapacityRecords
        rw [List.mem_flatten]
        exact ⟨R.capacityRecords, hmemBlock, hsRun⟩
      exact Int.le_trans (by exact_mod_cast h_er)
        (CapacityMultiRun.endpoint_le_latestAt hmem hlam)

/-- The compressed and exact multi-run record lists have the same maximum
capacity. -/
theorem maxCap_multiCapacityRecords_eq_multiEndpointRecords
    (runs : List (RealRun q k Tq Tk t)) :
    CapacityMultiRun.maxCap (multiCapacityRecords runs) =
      CapacityMultiRun.maxCap (multiEndpointRecords runs) := by
  apply Nat.le_antisymm
  · by_cases hne : multiCapacityRecords runs = []
    · rw [hne]
      simp [CapacityMultiRun.maxCap]
    · obtain ⟨r, hr, hrmax⟩ := CapacityMultiRun.maxCap_attained hne
      rw [← hrmax]
      unfold multiCapacityRecords at hr
      rw [List.mem_flatten] at hr
      obtain ⟨block, hblock, hrblock⟩ := hr
      rw [List.mem_map] at hblock
      obtain ⟨R, _hR, rfl⟩ := hblock
      obtain ⟨e, hce, hed, _hre, hleRow⟩ :=
        R.capacity_record_yields_exact_endpoint hrblock (Nat.le_refl r.cap)
      have hmemBlock : R.endpointRecords ∈ runs.map RealRun.endpointRecords := by
        rw [List.mem_map]
        exact ⟨R, _hR, rfl⟩
      have hmem : ({ cap := R.row e, endpoint := e } : CapacityRecord) ∈
          multiEndpointRecords runs := by
        unfold multiEndpointRecords
        rw [List.mem_flatten]
        exact ⟨R.endpointRecords, hmemBlock, RealRun.mem_endpointRecords hce hed⟩
      exact Nat.le_trans hleRow (CapacityMultiRun.cap_le_maxCap hmem)
  · by_cases hne : multiEndpointRecords runs = []
    · rw [hne]
      simp [CapacityMultiRun.maxCap]
    · obtain ⟨r, hr, hrmax⟩ := CapacityMultiRun.maxCap_attained hne
      rw [← hrmax]
      unfold multiEndpointRecords at hr
      rw [List.mem_flatten] at hr
      obtain ⟨block, hblock, hrblock⟩ := hr
      rw [List.mem_map] at hblock
      obtain ⟨R, _hR, rfl⟩ := hblock
      unfold RealRun.endpointRecords at hrblock
      rw [List.mem_map] at hrblock
      obtain ⟨i, hi, rfl⟩ := hrblock
      rw [List.mem_range] at hi
      have hce : R.c ≤ R.c + i := Nat.le_add_right _ _
      have hed : R.c + i ≤ R.d := by
        have hcd := R.hcd
        omega
      have hleRow : R.row (R.c + i) ≤ R.row (R.c + i) := Nat.le_refl _
      obtain ⟨s, hsRun, hrow_le_cap, _hes⟩ :=
        R.exact_endpoint_yields_capacity_record hce hed hleRow
      have hmemBlock : R.capacityRecords ∈ runs.map RealRun.capacityRecords := by
        rw [List.mem_map]
        exact ⟨R, _hR, rfl⟩
      have hmem : s ∈ multiCapacityRecords runs := by
        unfold multiCapacityRecords
        rw [List.mem_flatten]
        exact ⟨R.capacityRecords, hmemBlock, hsRun⟩
      exact Nat.le_trans hrow_le_cap (CapacityMultiRun.cap_le_maxCap hmem)

/-- The compressed multi-run records have exactly the same M0 `rmaxList` route
as the exact endpoint records. -/
theorem multiCapacityRecords_rmax_eq_multiEndpointRecords
    (runs : List (RealRun q k Tq Tk t)) :
    rmaxList ((multiCapacityRecords runs).map CapacityRecord.toRoute) =
      rmaxList ((multiEndpointRecords runs).map CapacityRecord.toRoute) := by
  change CapacityMultiRun.globalRoute (multiCapacityRecords runs) =
    CapacityMultiRun.globalRoute (multiEndpointRecords runs)
  rw [CapacityMultiRun.globalRoute_eq_winnerRoute,
      CapacityMultiRun.globalRoute_eq_winnerRoute]
  unfold CapacityMultiRun.winnerRoute
  rw [← maxCap_multiCapacityRecords_eq_multiEndpointRecords runs]
  rw [latestAt_multiCapacityRecords_eq_multiEndpointRecords]

/-- Concrete completeness plus the existing Q-cut/complete-record bridge. -/
theorem qcutClosed_eq_thresholdRoute_multiEndpointRecords_of_rowCovered
    {runs : List (RealRun q k Tq Tk t)} (hcover : RowCovered runs)
    {u : Nat} (ht : 0 < t) (hu : u ≤ t) :
    QCut.qcutClosed (fun e => (lcsLen q k t e : Int)) t u =
      CapacityMultiRun.thresholdRoute (multiEndpointRecords runs)
        (min (CapacityMultiRun.maxCap (multiEndpointRecords runs)) (t - u)) := by
  exact CapacityMultiRun.qcutClosed_eq_thresholdRoute_of_complete
    (completeAt_multiEndpointRecords_of_rowCovered hcover) ht hu

/-- **Concrete compressed-record Q-cut bridge.**  A genuine equal-symbol run
list covering the row, together with the exact per-rectangle ordinary/spike
records, computes `QCut.qcutClosed` without storing every endpoint. -/
theorem qcutClosed_eq_thresholdRoute_multiCapacityRecords_of_rowCovered
    {runs : List (RealRun q k Tq Tk t)} (hcover : RowCovered runs)
    {u : Nat} (ht : 0 < t) (hu : u ≤ t) :
    QCut.qcutClosed (fun e => (lcsLen q k t e : Int)) t u =
      CapacityMultiRun.thresholdRoute (multiCapacityRecords runs)
        (min (CapacityMultiRun.maxCap (multiCapacityRecords runs)) (t - u)) := by
  rw [qcutClosed_eq_thresholdRoute_multiEndpointRecords_of_rowCovered hcover ht hu]
  unfold CapacityMultiRun.thresholdRoute
  rw [← maxCap_multiCapacityRecords_eq_multiEndpointRecords runs]
  rw [← latestAt_multiCapacityRecords_eq_multiEndpointRecords]

end CapacityConcrete
