import Repair
import Capacity
import RunRectangleLcp
import RunHookSummary
import AffineEnvelope
import OwnerEnvelope
import RosBridge
import CommonBirth
import QBridge
import Interior
import RspSummary
import KDeleteAbstract
import KSkyline
import KDeleteROSA
import OwnerBridges
import OwnerCompress
import OwnerCorrect
import OwnerCorrectK
import WinnerPieces
import Gluing
import Phase12b
import KSuffix
import HookCut
import QCut
import RunRectangle
import HookDegenerate
import BoundaryPartition
import CapacityComplete
import AffineLifetime
import KDeleteEquivalence
import BlockWinnerNoReentry
import BoundaryRangeCount
import PayloadContraction
import CapacityMultiRun
import BoundaryCertificates
import BridgeEnvelope
import HookScan
import BoundaryZeroCertificates
import PayloadRouteAdapter
import RunHookCompressedScan
import BoundaryRecursive
import OwnerTemplateEquivalence
import CapacityConcrete
import RunHookCoverage
import BoundaryRunExtractor
import OwnerKBaselineEnvelope
import CapacityRunDecomposition
import BoundaryOptionalWindow
import OwnerKWindowDischarge
import CapacityAutomaticRunCover
import EnvelopeEssentialEvents
import EnvelopeExecutable
import EffectiveOwnerM3
import RunRectangleInitial
import PayloadErrorBound
import CreditRepairReduce
import CreditQEExpiry
import CreditBlockConv
import CreditCRT
import CreditCandidateCount
#check @HookCut.kcut_hook_decomposition
#check @QCut.qcut_future
#check @Repair.leftCtx
#check @Repair.run_grid_gamma_base
#check @OwnerEnv.qOwnerCands
#check @OwnerEnv.kOwnerCands
#check @OwnerEnv.active_not_interval
#check @QCut.qcut_length_and_latest_endpoint
#check @RunRect.run_grid_gamma_recurrence
#check @OwnerEnv.envWins_interval
#check @OwnerEnv.two_winner_interval
#check @OwnerEnv.bridgeRoute
#check @OwnerEnv.rspTemplates
#check @OwnerEnv.glue_A_leftToRight
#check @OwnerEnv.glue_P_threshold
#check @OwnerEnv.glue_U_union
#check @OwnerEnv.glue_interval
#check @OwnerEnv.centers
#check @OwnerEnv.runPairCands
#check @OwnerEnv.runPairCands_interval
#check @OwnerEnv.runPairTemplates_length
#check @OwnerEnv.runPairTemplates_interval
#check @OwnerEnv.interior_same_birth
#check @OwnerEnv.row_interval
#check @RosBridge.bridge_kappa_const
#check @RosBridge.route_better_iff_kappa
#check @QBridge.q_bridge_beats_cut
#check @CommonBirth.common_birth_winner_iff
#check @Interior.interior_bridge_route
#check @Interior.k_interior_bulk_equiv
#check @Interior.q_interior_bulk_max
#check @RspSummary.RspShape.threshold
#check @OwnerCorrect.field_candsOf
#check @OwnerCorrect.mkBridge_strict_interior
#check @OwnerCorrect.qOwnerCompressed_field
#check @OwnerCorrectK.field_kInteriorBulk
#check @OwnerCorrectK.bval_dropped
#check @OwnerCorrectK.bulkRoute_le_field
#check @OwnerCorrectK.kOwnerCompressed_field
#check @WinnerPieces.qOwnerCompressed_length_le_three
#check @WinnerPieces.kOwnerCompressed_length_le_three
#check @WinnerPieces.qOwner_filter_subset
#check @WinnerPieces.kOwner_filter_subset
#check @WinnerPieces.qOwner_field_three
#check @WinnerPieces.kEdge_rmax_eq
#check @WinnerPieces.kOwner_field_three
#check @Gluing.field_append
#check @Gluing.fieldBridges_append
#check @Gluing.field_flatten
#check @Gluing.glue_two
#check @Gluing.glue_pairs
#check @Phase12b.compress
#check @Phase12b.NoReentry
#check @Phase12b.segments_le_of_subset
#check @Phase12b.flatten_length_le
#check @Phase12b.segments_le_three_mul
#check @Phase12b.IsInterval
#check @Phase12b.segStart_label_ne
#check @Phase12b.segStarts_le_of_subset
#check @Phase12b.segments_le_three_mul_of_isInterval
#check @Phase12b.qCBCand_isInterval
#check @Phase12b.kSuffixWinner_isInterval
#check @Phase12b.routeOfKappa
#check @Phase12b.bridge_route_eq_routeOfKappa
#check @Phase12b.bridge_route_affine
#check @Phase12b.routeOfKappa_inj
#check @Phase12b.AffineOn
#check @Phase12b.bridge_affineOn
#check @Phase12b.overlay_breakpoints_le
#check @RspSummary.RspShape.value
#check @RspSummary.RspShape.le
#check @RspSummary.left_edge_context_rsp
#check @KDeleteAbstract.KDeleteFamily.best
#check @KDeleteAbstract.TrimClosed
#check @KDeleteAbstract.HasPrebirthShadow
#check @KDeleteAbstract.trim_kappa
#check @KDeleteAbstract.kdelete_step
#check @KDeleteAbstract.beats_delete_monotone
#check @KDeleteAbstract.better_future_bridge_blocks_before_birth
#check @KDeleteAbstract.shadow_not_beats
#check @KSkyline.k_suffix_winner_iff
#check @KDeleteROSA.rosaKDelete
#check @KDeleteROSA.rosa_trim_closed
#check @KDeleteROSA.rosa_has_prebirth_shadow
#check @KDeleteROSA.rosa_k_suffix_winner_iff
#check @OwnerBridges.qOwnerBridges
#check @OwnerBridges.kOwnerBridges
#check @OwnerBridges.mem_qOwnerBridges
#check @OwnerBridges.mem_kOwnerBridges
#check @OwnerBridges.Query.bridges
#check @OwnerBridges.mem_Query_bridges
#check @OwnerBridges.qOwnerBridges_birth
#check @OwnerCompress.Cand
#check @OwnerCompress.candOf
#check @OwnerCompress.field
#check @OwnerCompress.qOwnerCompressed
#check @OwnerCompress.kOwnerCompressed
#check @OwnerCompress.mem_qOwnerCompressed
#check @OwnerCompress.mem_kOwnerCompressed_iff
#check @OwnerCompress.kInteriorBulk_mem
#check @KSuffix.k_suffix_ceiling
#check @OwnerEnv.interior_bridge_value
#check @AffEnv.AffRoute.wins_convex
#check @AffEnv.AffRoute.wins_interval
#check @AffEnv.AffRoute.wins_list_convex
#check @RunHook.delta_ramp
#check @RunHook.delta_spike
#check @RunHook.delta_plateau
#check @RunHook.P_run_eq
#check @RunHook.U_plateau_max
#check @RunHook.A_run_eq
#check @Capacity.run_capacity_latest_endpoint
#check @RunRectLcp.repair_edge_right_rsp
#check @RunRect.run_rectangle_symbol_ne
#check @RunRect.run_rectangle_offset_lt
#check @RunRect.run_rectangle_offset_gt
#check @RunRect.run_rectangle_offset_eq
#check @Capacity.run_capacity_reaches
#check @RunRect.run_rectangle_rsp
#check @Repair.repair_left_boundary_support
#check @Repair.repair_right_boundary_support
#check @Repair.repair_edge_left_rsp
#check @Repair.repair_strict_interior_trivial

-- Phase D/E/G/lifetime closure files.
#check @RunHook.P_run_eq_all
#check @RunHook.U_plateau_max_all
#check @RunHook.A_run_eq_all
#check @Capacity.run_capacity_maxEndpoint?_correct
#check @Capacity.run_capacity_argmax_exists_iff
#check @Capacity.run_capacity_maxEndpoint?_eq_some_iff
#check @Capacity.run_capacity_two_records_sufficient
#check @Capacity.ordinaryRecord_wins_tie
#check @BoundaryPartition.rectPoint_strictInterior_or_onEdge
#check @BoundaryPartition.positive_context_edge_cover
#check @BoundaryPartition.context_edge_cover_or_strictInterior_zero
#check @BoundaryPartition.edgeMembershipCount_le_four
#check @BoundaryPartition.all_four_edges_of_singleton
#check @AffineLifetime.winner_change_forces_event
#check @AffineLifetime.criticalEvents_length_eq
#check @AffineLifetime.critical_scan_winner_iff
#check @AffineLifetime.lifetime_winner_reentry
#check @AffineLifetime.two_candidate_winner_iff
#check @AffineLifetime.ofBridge_wins_iff_route_rle

-- Bridge, no-reentry, range-count, and M4 contraction closure files.
#check @KDeleteEquivalence.rosaKDelete_best_eq_hookCut
#check @KDeleteEquivalence.rosaKDelete_best_eq_hookCut_of_pos_owner
#check @KDeleteEquivalence.rosaKDelete_beats_iff_bruteKCut_rle
#check @BlockWinnerNoReentry.qKeyWins_isInterval
#check @BlockWinnerNoReentry.kKeyWins_isInterval
#check @BlockWinnerNoReentry.segments_le_three_mul_of_isInterval_on
#check @BlockWinnerNoReentry.crossBlock_canonical_reentry
#check @BoundaryRangeCount.boundary_rsp_certificate_range_count_le_seven
#check @BoundaryRangeCount.boundary_range_count_le_seven
#check @BoundaryRangeCount.left_edge_certificate
#check @BoundaryRangeCount.right_edge_certificate
#check @PayloadContraction.intervalDot_eq_prefix_sub
#check @PayloadContraction.constantEndpointContraction_eq_contraction
#check @PayloadContraction.endpointShiftContraction_eq_contraction
#check @PayloadContraction.winnerIntervals_accum_eq_pointwise

-- Multi-run capacity, full boundary certificates, and bridge-envelope bridges.
#check @CapacityMultiRun.globalRoute_eq_winnerRoute
#check @CapacityMultiRun.latestAt_is_pointwise_max
#check @CapacityMultiRun.qcutClosed_eq_thresholdRoute_of_complete
#check @CapacityMultiRun.multiRunRecords_eq_per_run
#check @BoundaryCertificates.bottom_edge_certificate
#check @BoundaryCertificates.top_edge_certificate
#check @BoundaryCertificates.four_edge_certificate
#check @BoundaryCertificates.StringBoundaryRuns.certificate_range_count_le_seven
#check @BridgeEnvelope.qOwnerCandidates_winner_iff_bridgeWins
#check @BridgeEnvelope.kOwnerCandidates_rawWinner_iff_bridgeWins
#check @BridgeEnvelope.rosaKBaselineWinner_label_eq_some_iff
#check @KDeleteROSA.singleton_zero_not_mem_rosaCand

-- Scan, guarded boundary, and M4 route-adapter closure files.
#check @HookScan.scanCut_eq_hookCut
#check @HookScan.scanCut_eq_bruteKCut
#check @HookScan.delta_neg_one_classification
#check @BoundaryZeroCertificates.leftEdgeCertificateGuarded
#check @BoundaryZeroCertificates.rightEdgeCertificateGuarded
#check @BoundaryZeroCertificates.BoundaryRunsComplete.certificate_range_count_le_seven
#check @PayloadRouteAdapter.bridgeAffinePiece_shiftedEndpoint
#check @PayloadRouteAdapter.constantEndpointWinnerChain_eq_pointwise
#check @PayloadRouteAdapter.endpointShiftWinnerChain_eq_pointwiseSum
#check @KDeleteROSA.self_endpoint_not_mem_rosaCand

-- Run-compressed scan, recursive boundary, template, and concrete capacity closures.
#check @RunHookCompressedScan.U_run_eq_dense
#check @RunHookCompressedScan.P_run_eq_dense
#check @RunHookCompressedScan.A_run_eq_dense
#check @RunHookCompressedScan.foldedRunSummaries_eq_bruteKCut
#check @BoundaryRecursive.rightSingletonRecursiveCertificate
#check @BoundaryRecursive.topSingletonRecursiveCertificate
#check @BoundaryRecursive.completeToDirect_range_count_le_seven
#check @OwnerTemplateEquivalence.runPairTemplates_corrected_max_eq_actual
#check @OwnerTemplateEquivalence.qOwnerTemplates_length_le_three
#check @OwnerTemplateEquivalence.kOwnerTemplates_length_le_three
#check @CapacityConcrete.qcutClosed_eq_thresholdRoute_multiCapacityRecords_of_rowCovered
#check @CapacityConcrete.multiCapacityRecords_rmax_eq_multiEndpointRecords

-- Remaining coverage, extractor, K-baseline, and run-decomposition closures.
#check @RunHookCoverage.fold_pCompAll_eq_pScan
#check @RunHookCoverage.fold_uCompAll_eq_uScan
#check @RunHookCoverage.fold_aComp_eq_aScan
#check @RunHookCoverage.foldedHookCut_of_orderedCoverage
#check @BoundaryRunExtractor.rightCertificateOfStringRun
#check @BoundaryRunExtractor.topCertificateOfStringRun
#check @BoundaryRunExtractor.BoundaryWindow.certificate_range_count_le_seven
#check @OwnerKBaselineEnvelope.deletionAwareKOwnerEnvelope_eq_rmax
#check @OwnerKBaselineEnvelope.fixedKOwner_effectiveWinner_isInterval_of_window
#check @OwnerKBaselineEnvelope.kOwner_segments_le_three_mul_of_uniform
#check @CapacityRunDecomposition.RunCover.qcutClosed_eq_thresholdRoute_multiCapacityRecords
#check @CapacityRunDecomposition.RunDecomposition.complete_exact

-- Optional windows, K-window discharge, automatic capacity cover, and event dedup.
#check @BoundaryOptionalWindow.Window.certificate_range_count_le_seven
#check @BoundaryOptionalWindow.Window.exists_window_of_fullRunList_mem
#check @OwnerKWindowDischarge.hasRosaKWindow_of_mem_kOwnerBridges
#check @OwnerKWindowDischarge.fixedKOwner_canonicalWinner_isInterval_of_kOwnerBridges
#check @CapacityAutomaticRunCover.automaticCompleteAt
#check @CapacityAutomaticRunCover.automaticCapacityRecords_qcut
#check @AffineLifetime.essentialEvents_nodup
#check @AffineLifetime.essentialEvents_length_le
#check @AffineLifetime.essential_scan_winner_iff

-- Executable envelope scan and final fixed-owner M3 envelope.
#check @EnvelopeExecutable.scanEssential_exact
#check @EnvelopeExecutable.scanEssential_covers
#check @EnvelopeExecutable.scanEssential_change_mem_boundaries
#check @EffectiveOwnerM3.qEffectiveRoute_repair_or_cut
#check @EffectiveOwnerM3.kEffectiveRoute_eq_rmax_rosa_best_raw
#check @EffectiveOwnerM3.kEffectiveRoute_eq_threeField_of_strict
#check @EffectiveOwnerM3.q_and_k_effective_routes_are_owner_scoped

-- Unified initial-run recurrence and abstract M4 error bounds.
#check @RunRectInitial.run_rectangle_offset_eq_leftCtx
#check @RunRectInitial.run_rectangle_rsp_leftCtx
#check @RunRectInitial.run_grid_gamma_recurrence_leftCtx
#check @PayloadErrorBound.approxContraction_close
#check @PayloadErrorBound.chain_contraction_close
#check @PayloadErrorBound.chain_constantEndpointContraction_close
#check @PayloadErrorBound.chain_endpointShiftContraction_close
#check @PayloadErrorBound.chain_contraction_exact

-- ROSA_Credit_New_Results (the new credit-derivation package).
#check @CreditRepair.right_ctx_zero_of_not_right_end
#check @CreditRepair.carry_forces_k_right_end
#check @CreditRepair.qOwnerBridges_carry_unique
#check @CreditRepair.two_candidates_reproduce_envelope
#check @CreditCandidateCount.sum_map_le_card_mul
#check @CreditCandidateCount.sum_len_le_of_ordered
#check @CreditCandidateCount.sum_interior_le_of_ordered
#check @CreditCandidateCount.boundary_spots_length
#check @CreditCandidateCount.strictInterior_keep_le_two
#check @CreditCandidateCount.repair_candidate_bound
#check @CreditCandidateCount.repair_candidate_bound'
#check @QEExpiry.bridge_rle_const
#check @QEExpiry.scanAll_covered
#check @QEExpiry.scanAll_length_le
#check @QEExpiry.qExpirySkyline_spec
#check @QEExpiry.qExpirySkyline_covered
#check @QEExpiry.qExpirySkyline_length_le
#check @CreditBlockConv.convCoeff_eq_blockDot
#check @CreditBlockConv.blockDecomposition
#check @CreditBlockConv.chanConv_eq_chanDot
#check @CreditBlockConv.nBlocks_mul_ge
#check @CreditBlockConv.nBlocks_le
#check @CreditBlockConv.balance_div
#check @CreditBlockConv.balance_sum
#check @CreditCRT.crt_unique
#check @CreditCRT.crt_unique_three
#check @CreditCRT.two_natAbs_lt_of_le
