import HookCut

/-!
## Dense A/P/U scans for the fixed-row hook decomposition

This file gives raw-list prefix/suffix scans for the three hook pieces and
proves them exactly equal to the static lists used by `HookCut`.

* `A(s)` is a left-to-right prefix scan over endpoints `e < s`.
* `P(s)` is a right-to-left suffix scan, retaining endpoints with `delta e > s`.
* `U(s)` is the right-to-left maximum endpoint among endpoints with
  `delta e <= s`; `R(s)` is the ramp/plateau route generated from `U(s)`.

The scans are deliberately raw `List.range` scans.  They are not the eventual
GPU/run-compressed implementation, but they are the exact discrete reference
for it.
-/

open Route

namespace HookScan

/-- The unnormalised candidate route attached to endpoint `e`.  It is valid
when `0 < ell e`; this is the only case retained by the scans. -/
def routeAt (ell : Nat → Int) (e : Nat) : Route :=
  ⟨ell e, (e : Int)⟩

/-- `delta e = e - ell e`, possibly `-1`. -/
abbrev delta (ell : Nat → Int) (e : Nat) : Int := CutArith.delta ell e

/-- Endpoint filter for the prefix scan `A`.  The owner endpoint `s` itself is
excluded; it enters the scan only at the next index. -/
def aEligible (ell : Nat → Int) (s e : Nat) : Bool :=
  decide (e < s ∧ 0 < ell e)

/-- Endpoint filter for the suffix scan `P`.  The strict inequality `s < delta`
is the owner-boundary and `delta = -1` exclusion. -/
def pEligible (ell : Nat → Int) (s e : Nat) : Bool :=
  decide (0 < ell e ∧ (s : Int) < delta ell e)

/-- Endpoint filter for the endpoint-maximum suffix scan `U`. -/
def uEligible (ell : Nat → Int) (s e : Nat) : Bool :=
  decide (0 < ell e ∧ delta ell e ≤ (s : Int))

/-- `A(s)`: left-to-right prefix scan of eligible routes strictly left of the
owner. -/
def aScan (ell : Nat → Int) (t s : Nat) : Route :=
  (List.range t).foldl
    (fun acc e => if aEligible ell s e = true then rmax acc (routeAt ell e) else acc)
    unmatched

/-- `P(s)`: right-to-left suffix scan of routes whose deletion does not
truncate them. -/
def pScan (ell : Nat → Int) (t s : Nat) : Route :=
  (List.range t).foldr
    (fun e acc => if pEligible ell s e = true then rmax (routeAt ell e) acc else acc)
    unmatched

/-- `U(s)`: maximum eligible endpoint, with `-1` for the empty scan. -/
def uScan (ell : Nat → Int) (t s : Nat) : Int :=
  (List.range t).foldr
    (fun e acc => if uEligible ell s e = true then max (e : Int) acc else acc)
    (-1)

/-- `R(s)`: the ramp/plateau route generated by the endpoint-maximum scan. -/
def rScan (ell : Nat → Int) (t s : Nat) : Route :=
  if (s : Int) < uScan ell t s then CutArith.mk (uScan ell t s - (s : Int)) (uScan ell t s)
  else unmatched

/-- The three scans combined with the same route priority used by `HookCut`. -/
def scanCut (ell : Nat → Int) (t s : Nat) : Route :=
  rmax (aScan ell t s) (rmax (pScan ell t s) (rScan ell t s))

/-! ### List/table forms -/

/-- All `A(s)` prefix-scan results for `s = 0, ..., t`. -/
def aScanAll (ell : Nat → Int) (t : Nat) : List Route :=
  (List.range (t + 1)).map (aScan ell t)

/-- All `P(s)` suffix-scan results for `s = 0, ..., t`. -/
def pScanAll (ell : Nat → Int) (t : Nat) : List Route :=
  (List.range (t + 1)).map (pScan ell t)

/-- All `U(s)` suffix-scan results for `s = 0, ..., t`. -/
def uScanAll (ell : Nat → Int) (t : Nat) : List Int :=
  (List.range (t + 1)).map (uScan ell t)

/-! ### Basic validity and fold lemmas -/

theorem valid_routeAt (ell : Nat → Int) (e : Nat) (h : 0 < ell e) :
    Valid (routeAt ell e) := by
  unfold routeAt Valid
  dsimp only
  exact ⟨by omega, by omega, by intro hzero; omega⟩

theorem rmaxList_eq_foldr (l : List Route) :
    rmaxList l = l.foldr rmax unmatched := by
  induction l with
  | nil => rfl
  | cons r rs ih =>
      rw [rmaxList, List.foldr_cons, ih]

/-- A left fold of `rmax` is the initial route combined with the list maximum.
The validity hypotheses are exactly what is needed because `unmatched` is only
a right identity on valid routes. -/
theorem foldl_rmax_eq_rmax_init (l : List Route) (init : Route)
    (hinit : Valid init) (hvalid : ∀ r ∈ l, Valid r) :
    l.foldl rmax init = rmax init (rmaxList l) := by
  induction l generalizing init with
  | nil =>
      rw [List.foldl_nil, rmaxList, rmax_unmatched_right init hinit]
  | cons r rs ih =>
      rw [List.foldl_cons, rmaxList]
      have hr : Valid r := hvalid r (by simp)
      have hrs : ∀ x ∈ rs, Valid x := by
        intro x hx
        exact hvalid x (by simp [hx])
      rw [ih (rmax init r) (valid_rmax init r hinit hr) hrs]
      exact rmax_assoc init r (rmaxList rs)

/-! ### Exact correspondence with the static decomposition -/

theorem aScan_eq_ApartC (ell : Nat → Int) (t s : Nat) :
    aScan ell t s = HookCut.ApartC ell t s := by
  unfold aScan HookCut.ApartC CutArith.apartList routeAt
  rw [← List.foldl_filter]
  rw [← List.foldl_map]
  rw [foldl_rmax_eq_rmax_init]
  · rw [rmax_unmatched_left]
    · rfl
    · apply valid_rmaxList
      intro r hr
      rw [List.mem_map] at hr
      obtain ⟨e, he, rfl⟩ := hr
      rw [List.mem_filter] at he
      simp only [aEligible, decide_eq_true_eq] at he
      exact valid_routeAt ell e he.2.2
  · exact valid_unmatched
  · intro r hr
    rw [List.mem_map] at hr
    obtain ⟨e, he, rfl⟩ := hr
    rw [List.mem_filter] at he
    simp only [aEligible, decide_eq_true_eq] at he
    exact valid_routeAt ell e he.2.2

theorem pScan_eq_PpartC (ell : Nat → Int) (t s : Nat) :
    pScan ell t s = HookCut.PpartC ell t s := by
  unfold pScan HookCut.PpartC CutArith.ppartList routeAt pEligible delta CutArith.delta
  rw [rmaxList_eq_foldr]
  rw [List.foldr_map]
  rw [List.foldr_filter]

theorem uScan_eq_umax (ell : Nat → Int) (t s : Nat) :
    uScan ell t s = CutArith.umax ell t s := by
  unfold uScan CutArith.umax CutArith.uList uEligible delta CutArith.delta
  rw [List.foldr_map]
  rw [List.foldr_filter]

theorem rScan_eq_RpartC (ell : Nat → Int) (t s : Nat) :
    rScan ell t s = HookCut.RpartC ell t s := by
  unfold rScan HookCut.RpartC CutArith.rpart
  rw [uScan_eq_umax]

theorem scanCut_eq_hookCut (ell : Nat → Int) (t s : Nat) :
    scanCut ell t s = HookCut.hookCut ell t s := by
  unfold scanCut HookCut.hookCut
  rw [aScan_eq_ApartC, pScan_eq_PpartC, rScan_eq_RpartC]

theorem scanCut_eq_bruteKCut (ell : Nat → Int) (t s : Nat) :
    scanCut ell t s = CutArith.bruteKCut ell t s := by
  rw [scanCut_eq_hookCut]
  exact (HookCut.kcut_hook_decomposition ell t s).symm

/-! ### Empty scans -/

@[simp] theorem aScan_zero_length (ell : Nat → Int) (s : Nat) :
    aScan ell 0 s = unmatched := rfl

@[simp] theorem pScan_zero_length (ell : Nat → Int) (s : Nat) :
    pScan ell 0 s = unmatched := rfl

@[simp] theorem uScan_zero_length (ell : Nat → Int) (s : Nat) :
    uScan ell 0 s = -1 := rfl

@[simp] theorem rScan_zero_length (ell : Nat → Int) (s : Nat) :
    rScan ell 0 s = unmatched := by
  unfold rScan
  rw [uScan_zero_length]
  rw [if_neg (by omega : ¬ (s : Int) < (-1 : Int))]

@[simp] theorem scanCut_zero_length (ell : Nat → Int) (s : Nat) :
    scanCut ell 0 s = unmatched := by
  simp [scanCut, aScan_zero_length, pScan_zero_length, rScan_zero_length,
    rmax, rle]

/-! ### Owner endpoint and `delta = -1` boundaries -/

/-- The owner endpoint is not included in its own `A` prefix. -/
@[simp] theorem aEligible_owner_false (ell : Nat → Int) (s : Nat) :
    aEligible ell s s = false := by
  simp [aEligible]

/-- A positive owner endpoint enters `A` exactly at the next owner index. -/
theorem aEligible_owner_true_next (ell : Nat → Int) (s : Nat) (hpos : 0 < ell s) :
    aEligible ell (s + 1) s = true := by
  simp [aEligible, hpos]

/-- With `delta = -1`, an endpoint is always in the `U` side, never the `P`
side. -/
theorem delta_neg_one_classification (ell : Nat → Int) (s e : Nat)
    (hδ : delta ell e = -1) :
    ¬ ((s : Int) < delta ell e) ∧ delta ell e ≤ (s : Int) := by
  omega

theorem delta_neg_one_pEligible_false (ell : Nat → Int) (s e : Nat)
    (hδ : delta ell e = -1) :
    pEligible ell s e = false := by
  unfold pEligible
  rw [hδ]
  simp

theorem delta_neg_one_uEligible_true (ell : Nat → Int) (s e : Nat)
    (hpos : 0 < ell e) (hδ : delta ell e = -1) :
    uEligible ell s e = true := by
  unfold uEligible
  rw [hδ]
  simp [hpos]

/-! ### Endpoint tie-break -/

/-- The route priority used by the scans is the ROSA priority: equal lengths are
broken by the larger endpoint. -/
theorem rmax_same_len_prefers_larger_endpoint (len e₁ e₂ : Int) (h : e₁ ≤ e₂) :
    rmax (⟨len, e₁⟩ : Route) (⟨len, e₂⟩ : Route) = ⟨len, e₂⟩ := by
  have hle : rle (⟨len, e₁⟩ : Route) (⟨len, e₂⟩ : Route) := by
    unfold rle
    dsimp only
    exact Or.inr ⟨rfl, h⟩
  unfold rmax
  rw [if_pos hle]

end HookScan
